### ISSUE TITLE
flower morphology and children terms

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#105]
Suggested children of flower anatomy and morphology trait [(TO:0000499)](http://purl.obolibrary.org/obo/TO_0000499):

-  floret anatomy [(TO:0000274)](http://purl.obolibrary.org/obo/TO_0000274) 
    _- spikelet floret morphology trait (TO:0000274): see below_

- floret diameter - diameter of the floret 
     _- spikelet floret diameter (TO:0000855): see below_

- floret shape - shape of the floret 
     _- spikelet floret shape (TO:0000853): see below_

- lodicule anatomy [(TO:0006009)](http://purl.obolibrary.org/obo/TO_0006009) 
     _- lodicule morphology trait (TO:0006009)_
  _- lodicule length: TO:0000856_
  _- lodicule type: TO:0000857_

- flower organ size [(TO:0002600)](http://purl.obolibrary.org/obo/TO_0002600) - flower length 
 _- flower length (TO:0000860)_
  _- flower shape (TO:0000859)_
   _- flower diameter (TO:0000855)_

- sepal type; tepal type, lemma type
_These were not added- too vague_

- blossom end scar size [(SP:0000367)](http://purl.obolibrary.org/obo/SP_0000367) - synonym: distal fruit end scar

Reported by: alexandraviel

Original Ticket: [obo/plant-trait-ontology-to-requests/104](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/104)

**Comment by cooperl09** [comment]
**spikelet floret morphology trait (TO:0000274):**
was: * floret morphology trait: (TO:0000274):  A flower morphology trait (TO:0000499) which is a quality of a grass floret and its parts.
Revised: 
spikelet floret morphology trait (TO:0000274): A flower morphology trait (TO:0000499) which is a quality of a spikelet floret (PO:0009082).

Child terms: 
was: 
- floret color (TO:0000536): A floret morphology trait (TO:0000274) which is the color of the floret.
Revised: 
spikelet floret color (TO:0000536): A spikelet floret morphology trait (TO:0000274) which is the color of a spikelet floret (PO:0009082).

Was:
- floret diameter (TO:0000855): A floret morphology trait (TO:0000274) which is the diameter of a floret.

Revised: 
spikelet floret diameter (TO:0000855): A spikelet floret morphology trait (TO:0000274) which is the diameter of a spikelet floret (PO:0009082).

Was:
- floret shape (TO:0000853): A floret morphology trait (TO:0000274) which is the shape of a floret.

Revised: spikelet floret shape (TO:0000853): A spikelet floret morphology trait (TO:0000274) which is the shape of a spikelet floret (PO:0009082).

Was:	
- floret size (TO:0000854): A floret morphology trait (TO:0000274) which is the size of a floret.
	
Revised: spikelet floret size (TO:0000854): A spikelet floret morphology trait (TO:0000274) which is the size of a spikelet floret (PO:0009082).

**Comment by cooperl09** [comment]
Moved to be child terms of  'spikelet floret morphology trait'
Revised def'ns: 
lemma number: TO:0000208
- Was: A lemma and palea morphology trait (TO:0000079) which is the number of lemma (PO:0009037) in the grass flower (PO:0009001) (floret). 
Revised: 
A spikelet floret morphology trait (TO:0000274) which is the number of lemma (PO:0009037) in a spikelet floret (PO:0009082).
palea number (TO:0000209):  
- Was:  A lemma and palea morphology trait (TO:0000079) which is the number of palea (PO:0009038) in the grass flower (floret). 
- Revised: 
A spikelet floret morphology trait (TO:0000274) which is the number of  palea (PO:0009038) in a spikelet floret (PO:0009082).

Refers to: PATO:0001555 has number of
