### ISSUE TITLE
rachilla anatomy traits

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#106]
Proposed new parent term and definition:
\- Rachilla anatomy and morphology trait: Traits associated with changes in the anatomy or structure of the rachilla.

Proposed new children of term + definitions:
\- rachilla shape [\(CO\_320:0000125](http://purl.obolibrary.org/obo/\(CO\_320_0000125)\): Shape of rachilla. Refer to shape [PATO:0000052](http://purl.obolibrary.org/obo/PATO_0000052) 
\- rachilla hair type - 
\- rachilla length - Length of the rachilla. Refer to length [PATO:0000122](http://purl.obolibrary.org/obo/PATO_0000122) 

Reported by: alexandraviel

Original Ticket: [obo/plant-trait-ontology-to-requests/105](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/105)

**Comment by austinmeier** [comment]
created new terms:
rachilla anatomy and morphology trait (TO:0000954): def'n :An inflorescence branch anatomy and morphology trait (TO:0000784) that is associated with the spikelet rachilla (PO:0009080), is_a inflorescence branch anatomy and morphology trait (TO:0000784)
rachilla length (TO:0000972) def'n: An inflorescence branch anatomy and morphology trait (TO:0000784) which is associated with the length of a spikelet rachilla (PO:0009080). is_a rachilla anatomy and morphology trait (TO:0000954)
rachilla shape (TO:0000973) def'n: An inflorescence branch anatomy and morphology trait (TO:0000784) which is associated with the shape of a spikelet rachilla (PO:0009080). is_a rachilla anatomy and morphology trait (TO:0000954)
rachilla hair type (TO:0000974) def'n: An inflorescence branch anatomy and morphology trait (TO:0000784) which is associated with the pubescence of a spikelet rachilla (PO:0009080). is_a rachilla anatomy and morphology trait (TO:0000954)
