### ISSUE TITLE
infructescence axis (cob) traits

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#109]
Proposed new child \(term + definitions\) of  inflorescence color [\(TO:0000581](http://purl.obolibrary.org/obo/\(TO_0000581)\)
\- cob color - color [\(PATO:0000014](http://purl.obolibrary.org/obo/\(PATO_0000014)\) of the cob [\(PO:0020136](http://purl.obolibrary.org/obo/\(PO_0020136)\) + synonym : ear color 

Proposed new child \(term + definitions\) of  inflorescence shape [\(TO:0000268](http://purl.obolibrary.org/obo/\(TO_0000268)\)
\- cob shape - shape [\(PATO:0000052](http://purl.obolibrary.org/obo/\(PATO_0000052)\) of the cob [\(PO:0020136](http://purl.obolibrary.org/obo/\(PO_0020136)\) + synonym: ear shape

Proposed new child \(term + definitions\) of  inflorescence weight [\(TO:0000583](http://purl.obolibrary.org/obo/\(TO_0000583)\)
\- cob weigh t- weight [\(PATO:0000128](http://purl.obolibrary.org/obo/\(PATO_0000128) \) of the cob [\(PO:0020136](http://purl.obolibrary.org/obo/\(PO_0020136)\) + synonym: ear weight	

Reported by: alexandraviel

Original Ticket: [obo/plant-trait-ontology-to-requests/108](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/108)

**Comment by alexandraviel** [comment]
Proposed new child (term + definitions) of inflorescence color (TO:0000581)
Requested term : cob length
Trait description : length of cob	
related term(s) in PO: infructescence			
TO name : cob length
proposed TO definition: An infructescence axis anatomy and morphology trait (TO:0000921) associated with the length of a cob. Comment: Refers to length (PATO:0000122 ) 

Requested term : cob width
Trait description : width of cob	
related term(s) in PO: infructescence			
TO name : cob width
proposed TO definition: An infructescence axis anatomy and morphology trait (TO:0000921) associated with the width of a cob. Comment: Refers to width (PATO:0000921) 

Requested term : cob area
Trait description : area of cob	
related term(s) in PO: infructescence			
TO name : cob area
proposed TO definition: An infructescence axis anatomy and morphology trait (TO:0000921) associated with the area of a cob. Comment: Refers to area (PATO:0001323) 

Requested term : cob angle
Trait description : angle of cob	
related term(s) in PO: infructescence			
TO name : cob angle
proposed TO definition: An infructescence axis anatomy and morphology trait (TO:0000921) associated with the angle of a cob. Comment: Refers to angle (PATO:0002326)

**Comment by cooperl09** [comment]
In the Plant Ontology, the cob is an infructescence axis (PO:0025242), so these would all be child terms of infructescence axis anatomy and morphology trait (TO:0000921). 
When we refer to the cob, it is the axis of the ear of corn.

**Comment by ejohnson1** [comment]
Created new  child term: cob shape (TO:0000958): An infructescence axis anatomy and morphology trait (TO:0000921) associated with the shape of a cob. 
Added Xrefs: shape (PATO:0000052); TO_GIT:109

Created new child term: cob length (TO:0000959): An infructescence axis anatomy and morphology trait (TO:0000921) associated with the length of a cob.
Added Xrefs: length (PATO:000012); TO_GIT:109

Created new child term: cob width (TO:0000960): An infructescence axis anatomy and morphology trait (TO:0000921) associated with the width of a cob.
Added Xrefs: width (PATO:0000921); TO_GIT:109

Created new child term: cob area (TO:0000961): An infructescence axis anatomy and morphology trait (TO:0000921) associated with the area of a cob.
Added Xrefs: area (PATO:0001323); TO_GIT:109

Created new child term: cob angle (TO:0000962): An infructescence axis anatomy and morphology trait (TO:0000921) associated with the angle of a cob.
Added Xrefs: angle (PATO:0002326); TO_GIT:109
