### ISSUE TITLE
inflorescence bract morphology traits- including  husk traits

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#110]
proposed new children (term and definition) for leaf anatomy and morphology trait [(TO:0000748](http://purl.obolibrary.org/obo/%28TO_0000748))
- leaf color-&gt; husk color - color [(PATO:0000014](http://purl.obolibrary.org/obo/%28PATO_0000014)) of the husk [(PO:0006337](http://purl.obolibrary.org/obo/%28PO_0006337)-The leaf subtending an ear of corn and acting as outer envelope of the ear)
- leaf size -&gt; leaf length -&gt; husk length - length [(PATO:0000122](http://purl.obolibrary.org/obo/%28PATO_0000122) ) of the husk [(PO:0006337](http://purl.obolibrary.org/obo/%28PO_0006337))

Reported by: alexandraviel

Original Ticket: [obo/plant-trait-ontology-to-requests/109](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/109)

**Comment by cooperl09** [comment]
involucral bract spine presence (TO:0020120): was a child of TO:0000499 flower anatomy and morphology trait.

Moved to be is_a  inflorescence bract morphology trait (TO:0000819).  

Revised def'n: involucral bract spine presence (TO:0020120): An inflorescence bract morphology trait (TO:0000819) which is the presence of  spines on an involucral bract (PO:0009045).
Added xref to TO_GIT:110
