### ISSUE TITLE
silk trait

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#113]
child of inflorescence anatomy and morphology trait [\(TO:0000373](http://purl.obolibrary.org/obo/\(TO_0000373)\)
\- silk length - Measurement of [silk\(PO:0009074](http://purl.obolibrary.org/obo/silk\(PO_0009074) \) length [\(PATO:0000122](http://purl.obolibrary.org/obo/\(PATO_0000122) \) - [CO\_322:0000013](http://purl.obolibrary.org/obo/CO\_322_0000013) 

Reported by: alexandraviel

Original Ticket: [obo/plant-trait-ontology-to-requests/112](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/112)

**Comment by austinmeier** [comment]
revised def'n:  style length (TO:0011009), old: Length of the style in a pistil. new: A floral organ size (TO:0002600) that is associated with the length of the style (PO:0009074). Added DBXref: TO_GIT:113
moved style length (TO:0011009) to child_of floral organ length (TO:0011008) from floral organ size (TO:0002600)
