### ISSUE TITLE
fruit size

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#123]
request new synonym of  fruit size : pod size - An assay to determine the variation in the size [\(PATO:0000117](http://purl.obolibrary.org/obo/\(PATO_0000117)\) of the pod [\(PO:0009001](http://purl.obolibrary.org/obo/\(PO_0009001)\)

request new childs of fruit size:
\- fruit diameter + synonym: pod diameter - Diameter [\(PATO:0001334](http://purl.obolibrary.org/obo/\(PATO_0001334)\) of the fruits at mid-length [\(mm\).CO\_325:0000148](http://purl.obolibrary.org/obo/\(mm\).CO\_325_0000148)
\- fruit length + synonym : pod length- An assay to determine the variation in the length [\(PATO:0000122](http://purl.obolibrary.org/obo/\(PATO_0000122)\) of the pod [\(PO:0009001](http://purl.obolibrary.org/obo/\(PO_0009001)\)

request new children of grain size 
\- grain width -&gt; Brown rice width - Width of the grain monitored after dehulling but before polishing.

Reported by: alexandraviel

Original Ticket: [obo/plant-trait-ontology-to-requests/122](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/122)

**Comment by austinmeier** [comment]
Is grain thickness (TO:0000399) the same, or could we make grain width a synonym of grain thickness?
see issue #264 for grain thickness issues.

**Comment by austinmeier** [comment]
dehulled grain width (TO:0000402): A grain width (TO:0000975) which is associated with the width of the dehulled grain with pericarp (PO:0009084).
