### ISSUE TITLE
plant embryo morphology trait (TO:0000064)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#140]
existing term: 
embryo related trait 

proposed new name:
embryo anatomy and morphology trait

Reported by: lauramooray

Original Ticket: [obo/plant-trait-ontology-to-requests/139](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/139)

**Comment by ejohnson1** [comment]
Revised name and def'n: plant embryo anatomy and morphology trait (TO:0000064)
Was: plant embryo anatomy and morphology trait (TO:0000064), A plant structure anatomy and morphology trait (TO:0000839) which is associated with a plant embryo (PO:0009009).
New: plant embryo morphology trait (TO:0000064), A plant structure morphology trait (TO:0000839) which is a quality of a plant embryo (PO:0009009).

**Comment by cooperl09** [comment]
Moved plant embryo morphology trait (TO:0000064) to be a child of whole plant morphology trait (TO:0000398).
Was:
plant embryo morphology trait (TO:0000064), A plant structure morphology trait (TO:0000839) which is a quality of a plant embryo (PO:0009009).

Revised: plant embryo morphology trait (TO:0000064): A whole plant morphology trait (TO:0000398). which is a quality of a plant embryo (PO:0009009).

Child terms need to be reviewed.
