### ISSUE TITLE
multi-tissue plant structure morphology trait

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#147]
Proposed new child of anatomy and morphology trait [(TO:0000017](http://purl.obolibrary.org/obo/%28TO_0000017)):
multi-tissue plant sturcture anatomy and morphology trait: An anatomy and morphology trait [(TO:0000017](http://purl.obolibrary.org/obo/%28TO_0000017)) which is associated with a multi-tissue plant structure [(PO:0025496](http://purl.obolibrary.org/obo/%28PO_0025496)).

Proposed new child of multi-tissue plant sturcture anatomy and morphology trait [(TO:0000836](http://purl.obolibrary.org/obo/%28TO_0000836)):
cardinal organ part of a multi-tissue plant structure anatomy and morphology trait: A multi-tissue anatomy and morphology trait [(TO:0000836](http://purl.obolibrary.org/obo/%28TO_0000836)) which is associated with a cardinal organ part of a multi-tissue plant structure [(PO:0025498](http://purl.obolibrary.org/obo/%28PO_0025498)).

Reported by: lauramooray

Original Ticket: [obo/plant-trait-ontology-to-requests/146](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/146)

**Comment by ejohnson1** [comment]
Revised name and def'n: cardinal part of a multi-tissue plant structure anatomy and morphology trait (TO:0000837)
Was: cardinal part of a multi-tissue plant structure anatomy and morphology trait (TO:0000837), A plant structure anatomy and morphology trait (TO:0000839) which is associated with a cardinal organ part of a multi-tissue plant structure (PO:0025498).
New: cardinal part of a multi-tissue plant structure morphology trait (TO:0000837), A plant structure morphology trait (TO:0000839) which is a quality of a cardinal organ part of a multi-tissue plant structure (PO:0025498).

**Comment by ejohnson1** [comment]
Revised name and def'n: multi-tissue plant structure anatomy and morphology trait (TO:0000836).
Was: multi-tissue plant structure anatomy and morphology trait (TO:0000836), A plant structure anatomy and morphology trait (TO:0000839) which is associated with a multi-tissue plant structure (PO:0025496).
New: multi-tissue plant structure morphology trait (TO:0000836), A plant structure morphology trait (TO:0000839) which is a quality of a multi-tissue plant structure (PO:0025496).
