### ISSUE TITLE
plant structure morphology trait (TO:0000839)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#149]
Proposed new upper level term child of anatomy and morphology trait: 
plant structure anatomy and morphology trait: An anatomy and morphology trait [(TO:0000017](http://purl.obolibrary.org/obo/%28TO_0000017)) which is associated with a plant structure [(PO:0009011](http://purl.obolibrary.org/obo/%28PO_0009011)). 

Reported by: lauramooray

Original Ticket: [obo/plant-trait-ontology-to-requests/148](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/148)

**Comment by cooperl09** [comment]
ejohnson1 commented 10 minutes ago

revised definition:  plant structure morphology trait (TO:0000839) and def'n: A morphology trait (TO:0000017) which is a quality of a plant structure (PO:0009011).
(Original comment by @ejohnson1 - moved from tracker  #152)

**Comment by cooperl09** [comment]
Revised name and def'n:
Was: plant structure anatomy and morphology trait (TO:0000839): A morphology trait (TO:0000017) which is associated with a plant structure (PO:0009011).

Revised: 
plant structure morphology trait (TO:0000839): A plant morphology trait (TO:0000017) which is a morphological quality of a plant structure (PO:0009011).

**Comment by cooperl09** [comment]
revised:
plant structure morphology trait (TO:0000839): A plant morphology trait (TO:0000017) which is a quality of a plant structure (PO:0009011).
Took out second reference to 'morphological'

**Comment by ejohnson1** [comment]
Revised name and def'n: in vitro plant structure anatomy and morphology trait (TO:0000844).
Was: in vitro plant structure anatomy and morphology trait (TO:0000844), A plant structure anatomy and morphology trait (TO:0000839) which is associated with an in vitro plant structure. 
New: in vitro plant structure morphology trait (TO:00008440), A plant structure morphology trait (TO:0000839) which is a quality of an in vitro plant structure (PO:0000004).
