### ISSUE TITLE
collective plant structure morphology trait (TO:0000640) and child terms

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#150]
Proposed new child terms of plant structure anatomy and morphology trait:
- **collective plant structure anatomy and morphology trait**: A plant structure anatomy and morphology trait (TO:0000839) which is associated with a collective plant structure (PO:0025497).

Proposed new children of collective plant structure anatomy and morphology trait:
- **collective organ part structure anatomy and morphology trait (TO:0000841)**: A collective plant structure anatomy and morphology trait (TO:0000840) which is associated with a collective organ part structure (PO:0025269).
- **collective plant organ structure anatomy and morphology trait (TO:0000842)**: A collective plant structure anatomy and morphology trait(TO:0000840) which is associated with a collective plant organ structure (PO:0025007).

Reported by: lauramooray

Original Ticket: [obo/plant-trait-ontology-to-requests/149](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/149)

**Comment by cooperl09** [comment]
collective organ part structure anatomy and morphology trait (TO:0000841):  Revised def'n.
Was: A collective plant structure anatomy and morphology trait (TO:0000840) which is associated with a collective organ part structure (PO:0025269).
New:
A collective plant structure anatomy and morphology trait (TO:0000840) which is associated with the qualities of a collective organ part structure (PO:0025269).

**Comment by ejohnson1** [comment]
revised term collective plant structure morphology trait (TO:0000840) and def'n: A plant structure morphology trait (TO:0000839) which is a quality of a collective plant structure (PO:0025497).

**Comment by ejohnson1** [comment]
revised term collective organ part structure morphology trait (TO:0000841) and def'n: A collective plant structure morphology trait (TO:0000840) which is a quality of a collective organ part structure (PO:0025269).

**Comment by ejohnson1** [comment]
collective plant organ structure anatomy and morphology trait (TO:0000842):Revised name and def'n
Was: A collective plant structure anatomy and morphology trait (TO:0000840) which is associated with a collective plant organ structure (PO:0025007).
New: A collective plant structure morphology trait (TO:0000840) which is a quality of a collective plant organ structure (PO:0025007).
