### ISSUE TITLE
portion of plant tissue morphology trait

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#151]
Proposed new term, child of plant structure anatomy and morphology trait:
portion of plant tissue anatomy and morphology trait: A plant structure anatomy and morphology trait [(TO:0000839](http://purl.obolibrary.org/obo/%28TO_0000839)) which is associated with a portion of plant tissue [(PO:0009007](http://purl.obolibrary.org/obo/%28PO_0009007)).

Reported by: lauramooray

Original Ticket: [obo/plant-trait-ontology-to-requests/150](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/150)

**Comment by ejohnson1** [comment]
Revised name and def'n: portion of plant tissue anatomy and morphology trait (TO:0000843)
Was: portion of plant tissue anatomy and morphology trait (TO:0000843), A plant structure anatomy and morphology trait (TO:0000839) which is associated with a portion of plant tissue (PO:0009007).
New: portion of plant tissue morphology trait (TO:0000843), A plant structure morphology trait (TO:0000839) which is a quality of a portion of plant tissue (PO:0009007).
