### ISSUE TITLE
involucre bristle length

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#153]
Existing term involucre bristle length [\(TO:0000623](http://purl.obolibrary.org/obo/\(TO_0000623)\): The length of the bristles described as sterile inflorescence branch, similar to the one found in the Millet inflorescence.

This term needs to be reevaluated. 

Reported by: lauramooray

Original Ticket: [obo/plant-trait-ontology-to-requests/152](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/152)

**Comment by ejohnson1** [comment]
renamed bristle length (TO:0000643) to inflorescence bristle length (TO:0000643)
added "is_a" relationship between inflorescence bristle length (TO:0000643) and inflorescence anatomy and morphology trait (TO:0000373)
added xref (TO_GIT:153) to inflorescence bristle length (TO:0000643)
revised inflorescence bristle length (TO:0000643) def'n: An inflorescence morphology trait (TO:0000050) that is a quality of the bristles found on an inflorescence (PO:0009049).
revised involucre bristle length (TO:0000623) def'n: An inflorescence bristle length trait (TO:0000643) that is a quality of the bristles found on an involucre (PO:0009100).
added xref (TO_GIT:153) to involucre bristle length TO:0000623
created new term involucre morphology trait (TO:0000979): A collective phyllome structure morphology trait (TO:0000845) that is a quality of an involucre (PO:0009100).
added xref (TO_GIT:153) to involucre morphology trait (TO:0000979).

**Comment by cooperl09** [comment]
revised def'n:  **involucre bristle length (TO:0000623)**: 

was: An inflorescence bristle length trait (TO:0000643) that is a quality of the bristles found on an involucre (PO:0009100).

Revised: An inflorescence bristle length trait (TO:0000643) that is the length of the bristles found on an involucre (PO:0009100).

**Comment by cooperl09** [comment]
revised def'n:
* inflorescence bristle length (TO:0000643): 
was;  An inflorescence morphology trait (TO:0000050) that is a quality of the bristles found on an inflorescence (PO:0009049).

Revised: An inflorescence morphology trait (TO:0000050) that is the length of the bristles found on an inflorescence (PO:0009049).
