### ISSUE TITLE
inflorescence width is duplicated

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#159]
Inflorescence width [(TO:0000804](http://purl.obolibrary.org/obo/%28TO_0000804)):An inflorescence anatomy and morphology trait [(TO:0000373](http://purl.obolibrary.org/obo/%28TO_0000373)) which is associated with the width of an inflorescence [(PO:0009049](http://purl.obolibrary.org/obo/%28PO_0009049)). 

Inflorescence width [(TO:0000637](http://purl.obolibrary.org/obo/%28TO_0000637))

Reported by: lauramooray

Original Ticket: [obo/plant-trait-ontology-to-requests/158](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/158)

**Comment by cooperl09** [comment]
Terms were merged, with TO:0000637 now an alternate ID. Closing this ticket
