### ISSUE TITLE
Hilum color term request

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#163]
Title: Hilum color
Def: Color of the seed hilum.

I think that plants other than soybean have colored hilum, so this should be a general concept.

Reported by: maxglycine

Original Ticket: [obo/plant-trait-ontology-to-requests/162](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/162)

**Comment by cooperl09** [comment]
hilum color (TO:0000968) was added as a child of hilum morphology (TO:0000967):
A hilum morphology trait (TO:0000967) which is the color of a hilum (PO:0020063).
This was dealt with https://github.com/Planteome/plant-trait-ontology/issues/81
https://github.com/Planteome/plant-trait-ontology/issues/81
