### ISSUE TITLE
glume anatomy and morphology trait

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#166]
Proposed new child of inflorescence bract anatomy and morphology trait:
glume anatomy and morphology trait: An inflorescence bract anatomy and morphology trait [(TO:0000816](http://purl.obolibrary.org/obo/%28TO_0000816)) which is associated with a glume [(PO:0009039](http://purl.obolibrary.org/obo/%28PO_0009039)).

Reported by: lauramooray

Original Ticket: [obo/plant-trait-ontology-to-requests/165](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/165)

**Comment by cooperl09** [comment]
added term: glume shape (TO:0000978)
glume shape (TO:0000978): A glume anatomy and morphology trait (TO:0000869) with is associated with the shape of a glume (PO:0009039).
added xref: (TO_GIT:144) to glume shape (TO:0000978)
added relationship: glume anatomy and morphology trait (TO:0000869) is part_of spikelet anatomy and morphology trait (TO:0000657)

Originally submitted by ejohnson1 on tracker #144 

Changed Xref: TO_GIT:166- this tracker
