### ISSUE TITLE
dry fruit color

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#180]
Proposed new child of fruit color:
dry fruit color - A fruit color [\(TO:0002617](http://purl.obolibrary.org/obo/\(TO_0002617)\) which is associated with a fruit [\(PO:0009001](http://purl.obolibrary.org/obo/\(PO_0009001)\) that has been dried. Refer to color [PATO:0000014](http://purl.obolibrary.org/obo/PATO_0000014) and decreased water composition [\(PATO:0001801](http://purl.obolibrary.org/obo/\(PATO_0001801)\).

Reported by: lauramooray

Original Ticket: [obo/plant-trait-ontology-to-requests/179](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/179)

**Comment by ejohnson1** [comment]
Revised def'n of dry fruit color (TO:0000901)
Was: A fruit color (TO:0002617) which is associated with a fruit (PO:0009001) that has been dried. 
New: A fruit color (TO:0002617) which is the color of a fruit (PO:0009001) that has been dried.
