### ISSUE TITLE
seed weight (TO:0000181)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#196]
Current definition:
A seed yield [(TO:0000905](http://purl.obolibrary.org/obo/%28TO_0000905)) trait which is associated with the average weight of seeds [(PO:0009010](http://purl.obolibrary.org/obo/%28PO_0009010)) obtained from a plant, representing the overall yields or produce from the field. 

Current comment:
Refer to weight [(PATO:0000128](http://purl.obolibrary.org/obo/%28PATO_0000128)): A physical quality inhering in a bearer that has mass near a gravitational body.

Current relations:
is_a seed yield 

Proposed new definition:
A seed anatomy and morphology trait [(TO:0000184](http://purl.obolibrary.org/obo/%28TO_0000184)) which is associated with the weight of a seed [(PO:0009010](http://purl.obolibrary.org/obo/%28PO_0009010)).

Proposed new comment:
Seed weight is associated with the average weight of seeds [(PO:0009010](http://purl.obolibrary.org/obo/%28PO_0009010)) obtained from a plant, representing the overall yields or produce from the field. Seed weight has a component of seed yield [(TO:0000905](http://purl.obolibrary.org/obo/%28TO_0000905)) and seed quality [(TO:0000162](http://purl.obolibrary.org/obo/%28TO_0000162)). Refer to weight [(PATO:0000128](http://purl.obolibrary.org/obo/%28PATO_0000128)): A physical quality inhering in a bearer that has mass near a gravitational body.

Proposed new relations:
is_a seed anatomy and morphology trait 
has_part seed yield 
has_part seed quality

Reported by: lauramooray

Original Ticket: [obo/plant-trait-ontology-to-requests/195](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/195)

**Comment by cooperl09** [comment]
seed weight (TO:0000181)
revised comment: 
was: Seed weight is the average weight of seeds (PO:0009010) obtained from a plant, representing the overall yields or produce from the field.
Seed weight has a component of seed yield (TO:0000905), and seed quality (TO:0000162). Refer to weight (PATO:0000128): A physical quality inhering in a bearer that has mass near a gravitational body.

revised: Seed weight is a component of seed yield (TO:0000905), and seed quality (TO:0000162). Refer to weight (PATO:0000128): A physical quality inhering in a bearer that has mass near a gravitational body.
