### ISSUE TITLE
Importer Module needed

### ISSUE THREAD

**Issue by cooperl09** [Planteome/plant-trait-ontology#2]
Comment from Chris M:
planteome needs an importer module. This will simplify configuration for amigo and any other tools that consume planteome ontologies.

The first iteration of this can simply be an OWL file with the header that says:

import po.owl
import eo.owl
import ro.owl
import go.owl
import to.owl

etc

**Comment by cmungall** [comment]
## Background

importer files are fairly simple, and are very useful standard way of configuring a set of ontologies that are intended to be mutually coherent and used together.

An example:

 * http://purl.obolibrary.org/obo/upheno/monarch.owl

Standard purls are always used. You can map these to local files (e.g. for a dev instance) using a catalog xml file.

## URI

What should be the URI of the root ontology? We could register 'planteome' with obolibrary, but this is maybe not required, as we would not likely put class URIs in this space. Although we should be thinking ahead to all ontologies used in this project and what their ID spaces would be.

It may be simplest to keep the planteome owl file in the `po` idspace, e.g.

http://purl.obolibrary.org/obo/po/planteome.owl

With the source owl checked in to the po repo (so this ticket may belong in another tracker but that's not important).

## Ontologies

 * po
 * eo (I would really like to change the ID space of this one)
 * ro*
 * go*
 * to
 * ncbitaxon*
 * ...

For the ones marked * we may want to explore subsets in the future

### COs

It is probably simpler if we leave the COs out of the first iteration, but ultimately planteome.owl should cover the plant universe

This should probably go in a separate ticket.

## Jenkins job

Once we create the first iteration I'll create a jenkins job that will ensure overall coherence of the whole suite. 

## AmiGO conf

Once the importer is created, you can simplify your amigo conf by using this one file

To set up a dev instance you could use a catalog file to map the URIs to local files.

**Comment by cooperl09** [comment]
This issue was moved to Planteome/planteome-ontology-browsers#22
