### ISSUE TITLE
Leaflet number definition

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#211]
Leaflet number says that it is "An assay to detrmine the variation the number of leaves".  I think "leaves" should be "leaflets".  Also, should the definition be more like this "Variation the in the number of leaflets originating from the petiole of a compound leaf"?

Reported by: maxglycine

Original Ticket: [obo/plant-trait-ontology-to-requests/210](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/210)

**Comment by cooperl09** [comment]
Revised: 
id: TO:0002636
name: leaflet number
def:  A compound leaf morphology trait (TO:0001121) which is the number of leaflets (PO:0020049) in a compound leaf (PO:0020043).
 xref: TO_GIT:211
