### ISSUE TITLE
Add leaflet length, width and area

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#216]
Title: leaflet length Def: A compound leaf anatomy and morphology trait (TO:TBA) which is associated with the length of a leaflet [(PO:0020049](http://purl.obolibrary.org/obo/%28PO_0020049)) of a compound leaf [(PO:0020043](http://purl.obolibrary.org/obo/%28PO_0020043)).  Child of: compound leaf anatomy and morphology trait (TO:TBA).

Title: leaflet width Def: A compound leaf anatomy and morphology trait (TO:TBA) which is associated with the width of a leaflet [(PO:0020049](http://purl.obolibrary.org/obo/%28PO_0020049)) of a compound leaf [(PO:0020043](http://purl.obolibrary.org/obo/%28PO_0020043)).  Child of: compound leaf anatomy and morphology trait (TO:TBA).

Title: leaflet area Def: A compound leaf anatomy and morphology trait (TO:TBA) which is associated with the area of a leaflet [(PO:0020049](http://purl.obolibrary.org/obo/%28PO_0020049)) of a compound leaf [(PO:0020043](http://purl.obolibrary.org/obo/%28PO_0020043)).  Child of: compound leaf anatomy and morphology trait (TO:TBA).

Reported by: maxglycine

Original Ticket: [obo/plant-trait-ontology-to-requests/215](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/215)

**Comment by cooperl09** [comment]
These have been created: 
TO:0001115- leaflet length
def: A leaflet morphology trait (TO:0001113) which is the length (PATO:0000122 ) of a leaflet (PO:0020049).
xref: TO_GIT:216
'part of' some 'leaflet size'

TO:0001118- leaflet width
def:  A leaflet morphology trait (TO:0001113) which is the width (PATO:0000921) of a leaflet (PO:0020049). 
xref: TO_GIT:216
'part of' some 'leaflet size'

TO:0001114- leaflet area
def: A leaflet morphology trait (TO:0001113) which is the area (PATO:0001323) of a leaflet (PO:0020049).
xref: TO_GIT:216
'part of' some 'leaflet size'
