### ISSUE TITLE
alignment of bracts in TO and PO

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#227]
.....is\_a [TO:0000736](http://purl.obolibrary.org/obo/TO_0000736) \! plant organ anatomy and morphology trait
......is\_a [TO:0000747](http://purl.obolibrary.org/obo/TO_0000747) \! phyllome anatomy and morphology trait
.......is\_a [TO:0000815](http://purl.obolibrary.org/obo/TO_0000815) \! bract anatomy and morphology trait
........is\_a [TO:0000816](http://purl.obolibrary.org/obo/TO_0000816) \! inflorescence bract anatomy and morphology trait
.........is\_a [TO:0000079](http://purl.obolibrary.org/obo/TO_0000079) \! lemma and palea anatomy and morphology trait \*\*\* 

question 1: can a syn "flower bract" be added to the leaf node? I believe flower bract is equivalent to the union of lemma or palea.

question 2: the hierarchy above does not align with PO, in which flower bract and inflorescence bract are sibs:

.....is\_a [PO:0006001](http://purl.obolibrary.org/obo/PO_0006001) \! phyllome
......is\_a [PO:0009055](http://purl.obolibrary.org/obo/PO_0009055) \! bract
.......is\_a [PO:0009034](http://purl.obolibrary.org/obo/PO_0009034) \! flower bract
........is\_a [PO:0009037](http://purl.obolibrary.org/obo/PO_0009037) \! lemma \*\*\* 
........is\_a [PO:0009038](http://purl.obolibrary.org/obo/PO_0009038) \! palea \*\*\* 
.......is\_a [PO:0009054](http://purl.obolibrary.org/obo/PO_0009054) \! inflorescence bract \*\*\* 

See Jenkins report for more of these.

Reported by: cmungall

Original Ticket: [obo/plant-trait-ontology-to-requests/226](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/226)

**Comment by ejohnson1** [comment]
Revised name and def'n: trichome anatomy and morphology trait (TO:0000911)
Was: trichome anatomy and morphology trait (TO:0000911), A plant structure anatomy and morphology trait (TO:0000839) which is associated with a trichome (PO:0000282).
New: trichome morphology trait (TO:0000911), A plant structure morphology trait (TO:0000839) which is a quality of a trichome (PO:0000282).

**Comment by cooperl09** [comment]
Fixed in #390
