### ISSUE TITLE
Specific leaf/leaflet weight request

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#231]
I need a drought stress related term "specific leaflet weight"  defined as the weight of a leaflet/surface area.  We may also need "specific leaf weight" defined similarly.  These would be children of water stress trait [(TO:0000237](http://purl.obolibrary.org/obo/%28TO_0000237%29).

Reported by: maxglycine

Original Ticket: [obo/plant-trait-ontology-to-requests/231](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/231)

**Comment by cooperl09** [comment]
These have been created:
TO:0001120- specific leaflet weight
def:  A leaflet weight (TO:0001117) which is the ratio of leaflet weight to leaflet area (TO:0001114).  
xref: TO_GIT:231
synonym: leaflet specific weight (exact)

TO:0001122  specific leaf weight
def:  A leaf weight (TO:0000505) which is the ratio of leaf weight to leaf area (TO:0000540).  
xref: TO_GIT:231
