### ISSUE TITLE
new tassel length child terms

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#272]
Traits described in <a href="http://www.ncbi.nlm.nih.gov/pubmed/22125498">Brown et al 2011</a> that might be children of 
    TO:0000798, tassel inflorescence length/ TO:0000788, tassel infloresence and morphology trait.
(1) tassel branch zone, "length of tassel between lowest and uppermost branches"
## (2) tassel spike length, "length of tassel from uppermost branch to tip"

Reported by: mlschaeffer

Original Ticket: [obo/plant-trait-ontology-to-requests/272](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/272)

**Comment by cooperl09** [comment]
name: tassel spike length TO:0000939
+def: "An inflorescence axis length (TO:0001072) which is the length of the first order tassel inflorescence axis (PO:0006324) from the most distal branch point to the tip of the tassel inflorescence (PO:0020126)." 
synonym: "first order tassel inflorescence axis length (exact)" EXACT []
is_a: TO:0001072 ! inflorescence axis length
relationship: part_of TO:0000798 ! tassel inflorescence length


id: TO:0000940
name: tassel branch zone length
def: "An inflorescence axis length (TO:0001072) which is the length of the first order tassel inflorescence axis (PO:0006324) where the tassel inflorescence branches (PO:0006323) arise." [PMID:28373892, TO:cooperl]
xref: TO_GIT:272
is_a: TO:0001072 ! inflorescence axis length
relationship: part_of TO:0000798 ! tassel inflorescence length
