### ISSUE TITLE
New term request: grain protein content

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#278]
Closest fit is "protein content" TO 0000598. Suggest child term of this with defintion:
per cent of grain dry weight that is protein
This trait is pretty important to seed quality. Since maize grain is not really a seed, like keeping it more general to include the other cereals.

Reported by: mlschaeffer

Original Ticket: [obo/plant-trait-ontology-to-requests/278](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/278)

**Comment by celineaubert** [comment]
I also need this trait. 

Definition: A protein content trait (TO:0000598) which is the amount of protein (CHEBI_36080) in a caryopsis fruit (PO:0030104).
Ref: https://doi.org/10.1533/9781855737129.1.71

Exact syn: caryopsis fruit protein content

SubClass of:  TO:0000598 protein content

**Comment by cooperl09** [comment]
New term: 
grain protein content TO:0001136: A protein content trait (TO:0000598) which is the amount of protein (CHEBI:36080) in a caryopsis fruit (PO:0030104).

related synonyms: 
- kernel protein content (related)
