### ISSUE TITLE
New term: kernel row number per ear

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#286]
-kernel row number per ear [(TO:0000687](http://purl.obolibrary.org/obo/(TO_0000687)): A infructescence yield trait [(TO:0000936](http://purl.obolibrary.org/obo/(TO_0000936)) associated with the number of rows of kernels per ear infructescence [(PO:0025597](http://purl.obolibrary.org/obo/(PO_0025597)).

Comment: In maize, kernel row number is counted on the central, widest part of the uppermost ear infructescence [(PO:0025597](http://purl.obolibrary.org/obo/(PO_0025597)) on the plant. 
http://www.maizegdb.org/cgi-bin/displaytraitrecord.cgi?id=51580

Reported by: cooperl09

Original Ticket: [obo/plant-trait-ontology-to-requests/287](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/287)

**Comment by ejohnson1** [comment]
revised def'n of kernel row number per ear (TO:0000687): An ear infructescence anatomy and morphology trait (TO:0000920) associated with the number of rows of kernels per ear infructescence (PO:0025597).
added xref: (TO_GIT:286) to kernel row number per ear (TO:0000687)
