### ISSUE TITLE
pericarp anatomy and morphology trait (TO:0000945)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#292]
Created new term: pericarp anatomy and morphology trait (TO:0000945): A portion of plant tissue anatomy and morphology trait (TO:0000843) which is associated with the qualities of the pericarp (PO:0009084).

Moved pericarp color [(TO:0000707](http://purl.obolibrary.org/obo/(TO_0000707)) to be a child of pericarp anatomy and morphology trait [(TO:0000945](http://purl.obolibrary.org/obo/(TO_0000945).
Revised def'n: was: Describes the color of fruit wall (pericarp).

New def'n: A pericarp anatomy and morphology trait [(TO:0000945](http://purl.obolibrary.org/obo/(TO_0000945)) that is associated with the color of the pericarp [(PO:0009084](http://purl.obolibrary.org/obo/(PO_0009084)).

Added Xref to color [PATO:0000014](http://purl.obolibrary.org/obo/PATO_0000014)
Added part_of relation to fruit color [(TO:0002617](http://purl.obolibrary.org/obo/(TO_0002617)) and secondary is_a relation to fruit quality trait [(TO:0002728](http://purl.obolibrary.org/obo/(TO_0002728)).
Need to come back and look at the synonyms.

Reported by: cooperl09

Original Ticket: [obo/plant-trait-ontology-to-requests/293](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/293)

**Comment by cooperl09** [comment]
- pericarp anatomy and morphology trait (TO:0000945)
- pericarp color (TO:0000707)
- pericarp texture (TO:0002623)
Fixed xref to TO_GIT:292 (was 293) for all three.
