### ISSUE TITLE
mesocarp anatomy and morphology trait and child terms

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#294]
Added terms: 
- mesocarp anatomy and morphology trait [(TO:0000948](http://purl.obolibrary.org/obo/(TO_0000948)): A portion of plant tissue anatomy and morphology trait [(TO:0000843](http://purl.obolibrary.org/obo/(TO_0000843)) which is associated with the qualities of the mesocarp [(PO:0009087](http://purl.obolibrary.org/obo/(PO_0009087)).
-  mesocarp color [(TO:0002619](http://purl.obolibrary.org/obo/(TO_0002619)):A mesocarp anatomy and morphology trait [(TO:0000948](http://purl.obolibrary.org/obo/(TO_0000948)) that is associated with the qualities of the mesocarp [(PO:0009087](http://purl.obolibrary.org/obo/(PO_0009087)). added xref to PATO color term [[PATO:0000014](http://purl.obolibrary.org/obo/[PATO_0000014)]

Reported by: austinmeier

Original Ticket: [obo/plant-trait-ontology-to-requests/295](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/295)

**Comment by cooperl09** [comment]
Revised def'n: 
mesocarp color (TO:0002619): A mesocarp anatomy and morphology trait (TO:0000948) that is associated with the color of the mesocarp (PO:0009087).
- fixed xref to correct TO_GIT: 294
