### ISSUE TITLE
exocarp anatomy and morphology trait and child terms

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#295]
Created new terms: 

- Revised:  exocarp anatomy and morphology trait (TO:0000906): A portion of plant tissue anatomy and morphology trait (TO:0000843) which is associated with the qualities of the exocarp (PO:0009085). 
(Renamed: was epicarp anatomy and morphology trait)

- Added child term: exocarp color (TO:0002620): An exocarp anatomy and morphology trait (TO:0000906) that is associated with the qualities of the exocarp (PO:0009085). 
- exact syn: epicarp color
- Added Xrefs to color (PATO:0000014)

-Added Xref to TO_GIT to replace old SourceForge tracker in exocarp thickness [(TO:0000907](http://purl.obolibrary.org/obo/(TO_0000907)): [OBO_SF_TO:3533464](http://purl.obolibrary.org/obo/OBO_SF_TO_3533464)

Reported by: austinmeier

Original Ticket: [obo/plant-trait-ontology-to-requests/296](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/296)

**Comment by cooperl09** [comment]
exocarp anatomy and morphology trait (TO:0000906) and child terms; exocarp color (TO:0002620) and exocarp thickness (TO:0000907):
- fixed PO:id for exocarp in definitions and GitHub tracker # 295
- fixed xref to correct TO_GIT: 295

**Comment by cooperl09** [comment]
Moved epicarp texture (TO:0002624) to be is_a exocarp anatomy and morphology trait (TO:0000906). Added Xref: TO_GIT: 295
- revised name: exocarp texture (TO:0002624)- 
This was was changed in commit bec2d852964ecfddbeb7e1a73fc4a98e75cb13c4 on July 23, 2015 but does not seem to be there.

**Comment by cooperl09** [comment]
Revised def'n:  exocarp color (TO:0002620): An exocarp anatomy and morphology trait (TO:0000906) that is associated with the color of the exocarp (PO:0009085).
Added Xrefs to color (PATO:0000014)
