### ISSUE TITLE
new terms: corolla anatomy and morphology trait (TO:0000950) and child terms

### ISSUE THREAD

**Issue by cooperl09** [Planteome/plant-trait-ontology#299]
Created a couple of new terms to describe the corolla: 

corolla anatomy and morphology trait (TO:0000950):
A collective phyllome structure anatomy and morphology trait (TO:0000845) which is associated with the qualities of a corolla (PO:0009059).  

corolla color (TO:0000951): A corolla anatomy and morphology trait (TO:0000950) that is associated with the color of a corolla (PO:0009059). Added Xref to PATO:0000014

**Comment by ejohnson1** [comment]
Revised name and def'n: corolla color (TO:0000951)
Was: corolla color (TO:0000951), A corolla anatomy and morphology trait (TO:0000950) that is associated with the color of a corolla (PO:0009059).
New: corolla color (TO:0000951),A corolla morphology trait (TO:0000950) that is the color of a corolla (PO:0009059).
