### ISSUE TITLE
'pericarp color' should not be a subclass of 'fruit quality trait'

### ISSUE THREAD

**Issue by cmungall** [Planteome/plant-trait-ontology#312]
As pericarps are part of fruit

See also #292 

Example of downstream problem:

<img width="1179" alt="screen shot 2015-11-11 at 5 02 03 pm" src="https://cloud.githubusercontent.com/assets/50745/11107799/f5203352-8895-11e5-9331-4404d22f4334.png">

**Comment by cooperl09** [comment]
This is fixed, closing.
