### ISSUE TITLE
inappropriate subclasses of 'abiotic stress trait'

### ISSUE THREAD

**Issue by cmungall** [Planteome/plant-trait-ontology#324]
The following are currently subclasses; for many, a different relation (e.g. causal) should be used. I have checked the ones that should remain subclasses

 - [ ] [TO:0000051](http://purl.obolibrary.org/obo/TO_0000051) ! stem strength
 - [ ] [TO:0000068](http://purl.obolibrary.org/obo/TO_0000068) ! lodging incidence
 - [ ] [TO:0000084](http://purl.obolibrary.org/obo/TO_0000084) ! root number
 - [ ] [TO:0000093](http://purl.obolibrary.org/obo/TO_0000093) ! root pulling force
 - [ ] [TO:0000115](http://purl.obolibrary.org/obo/TO_0000115) ! root mass density
 - [ ] [TO:0000131](http://purl.obolibrary.org/obo/TO_0000131) ! leaf water potential
 - [ ] [TO:0000157](http://purl.obolibrary.org/obo/TO_0000157) ! canopy temperature <-- this is an environmental condition, NOT a trait
 - [X] [TO:0000161](http://purl.obolibrary.org/obo/TO_0000161) ! radiation response trait
 - [ ] [TO:0000233](http://purl.obolibrary.org/obo/TO_0000233) ! root volume
 - [X] [TO:0000237](http://purl.obolibrary.org/obo/TO_0000237) ! water stress trait
 - [ ] [TO:0000257](http://purl.obolibrary.org/obo/TO_0000257) ! root branching
 - [ ] [TO:0000279](http://purl.obolibrary.org/obo/TO_0000279) ! root weight
 - [X] [TO:0000432](http://purl.obolibrary.org/obo/TO_0000432) ! temperature response trait
 - [ ] [TO:0000471](http://purl.obolibrary.org/obo/TO_0000471) ! root penetration index
 - [x] [TO:0000482](http://purl.obolibrary.org/obo/TO_0000482) ! chemical stress sensitivity
 - [ ] [TO:0000510](http://purl.obolibrary.org/obo/TO_0000510) ! penetrated to total root ratio
 - [ ] [TO:0000515](http://purl.obolibrary.org/obo/TO_0000515) ! relative growth rate
 - [ ] [TO:0000519](http://purl.obolibrary.org/obo/TO_0000519) ! rooting depth
 - [ ] [TO:0000566](http://purl.obolibrary.org/obo/TO_0000566) ! stomatal frequency
 - [ ] [TO:0000576](http://purl.obolibrary.org/obo/TO_0000576) ! stem length
 - [X] [TO:0002693](http://purl.obolibrary.org/obo/TO_0002693) ! gravity response trait
 - [ ] [TO:0002735](http://purl.obolibrary.org/obo/TO_0002735) ! straighthead
 - [ ] [TO:0020087](http://purl.obolibrary.org/obo/TO_0020087) ! root cracking
\

**Comment by cooperl09** [comment]
These have been fixed, except for:
TO:0000068 ! lodging incidence
 TO:0000157 ! canopy temperature
TO:0000131 ! leaf water potential
These need additional work.
