### ISSUE TITLE
missing term: 'epicormic shoot system number'

### ISSUE THREAD

**Issue by leova** [Planteome/plant-trait-ontology#332]
Was looking for an equivalent to CO_325:0000024 'number of suckers'

(sucker is exact synonym of PO:0004546 epicormic shoot system)

**Comment by ejohnson1** [comment]
Propose new SubClasses of "shoot system morphology trait (TO:0000077):
"shoot-borne shoot system morphology trait"
"epicormic shoot system morphology trait"
"epicormic shoot system number trait"

**Comment by cooperl09** [comment]
Agreed, please add these new sub classes of "shoot system morphology trait (TO:0000077)

You could try adding them with the new TermGenie tool: http://to.termgenie.org
but you will need to create a login.

**Comment by ejohnson1** [comment]
added new term: shoot-borne shoot system morphology trait (TO:0000988): A shoot system morphology trait (TO:0000077) that is a quality of a shoot-borne shoot system (PO:0004545).
added dbxref: TO_GIT: 332
added new term: epicormic shoot system morphology trait (TO:0000989): A shoot-borne shoot system morphology trait (TO:0000988) that is a quality of an epicormic shoot system (PO:0004546).
added dbxref: TO_GIT:332

**Comment by ejohnson1** [comment]
added new term: epicormic shoot system number (TO:0000991), An epicormic shoot system morphology trait (TO:0000989) which is the number of epicormic shoot systems (PO:0004546).
added dbxref: TO_GIT:332
