### ISSUE TITLE
Need cotyledon color term

### ISSUE THREAD

**Issue by maxglycine** [Planteome/plant-trait-ontology#335]
Cotyledon color
Def: The color (PATO:PATO_0000014) of the cotyledon (PO:0020030).

**Comment by austinmeier** [comment]
#353

**Comment by cooperl09** [comment]
Rex, this term has been created for plant embryo cotyledon color:
plant embryo cotyledon color (TO:0000980): A plant embryo cotyledon morphology trait (TO:0000775) which is the color of a plant embryo cotyledon (PO:0025470).
added xref: PATO:0000014

If you are looking for a term to describe the color of cotyledons after germination, there is already one for seedling cotyledon color:

seedling cotyledon color (TO:0000750):  A seedling cotyledon morphology trait (TO:0000774) which is the color of a seedling cotyledon (PO:0025471).

Closing this Issue.
