### ISSUE TITLE
New term request: Root length density

### ISSUE THREAD

**Issue by KarthikaRajendran** [Planteome/plant-trait-ontology#352]
Definition: The length of roots present in a unit volume of soil
Method: Calculated using both root length measured and soil volume from where the root comes.
Scale: cm cm-3
Reference: Australian Journal of Agricultural Research, 2005, 56, 971-981.

**Comment by phismith** [comment]
The definition does not make it clear why this is a case of *density*
BS

**Comment by austinmeier** [comment]
After some discussion, we have decided to use root length (TO:0000227).
