### ISSUE TITLE
New term request: Cotyledon colour

### ISSUE THREAD

**Issue by KarthikaRajendran** [Planteome/plant-trait-ontology#353]
Definition:A trait describing the colour of cotyledon
Method:To be observed on seeds less than three months old
Scale:1 to 3 colour scale
Reference:Key access and utilization descriptors for lentil genetic resources (http://www.bioversityinternational.org/e-library/publications/detail/key-access-and-utilization-descriptors-for-lentil-genetic-resources/)

**Comment by phismith** [comment]
Traits do not describe.
People describe by using words.
The trait here *is *the color of the cotyledon
BS

**Comment by austinmeier** [comment]
From the reference provided: "To be observed on seeds less than three months old."  If lentil seeds are still considered "seedlings" before a seed is 3 months old we can use the TO term:

 seedling cotyledon color (TO:0000750): A seedling cotyledon morphology trait (TO:0000774) which is the color of a seedling cotyledon (PO:0025471).

**Comment by austinmeier** [comment]
It is true that we should include the PATO ID of any term where we use it, but we have traditionally put the PATO ID in the comments or DBXrefs section of the OBO edit program.  I am not sure how these should be handled in Protege.  Maybe Chris could weigh in?

**Comment by KarthikaRajendran** [comment]
Dear all, cotyledon colour is the seed quality trait. Usually it is yellow, red and orange in colour. It is not the seedling trait. It is said to be observed on seeds less than three months old because when seeds get old the colour will become dull some what. Usually the phenolic compounds in the seed determines the colour retention of seed cotyledon and seed coat colour.

**Comment by KarthikaRajendran** [comment]
Lentil seeds have very little or no endosperm in it. Cotyledons serves the food reserve for the embryo and account for more than 80% of seed weight. Eventually they are called as cotyledon colour.

**Comment by KarthikaRajendran** [comment]
Definition: A trait used to classify the cotyledon color.

**Comment by cooperl09** [comment]
Thank you for the clarification- in the PO this would be called "plant embryo cotyledon (PO:0025470)' since it is assessed on the seeds before germination.

**Comment by austinmeier** [comment]
As for Rex's terms request, I would point you to the PO definition of seedling development stage (PO:0007131): A sporophyte vegetative stage (PO:0007134) that succeeds the seed germination stage (PO:0007057) and terminates with the development of the first adult vascular leaf (PO:0006340). 

If your soy trait is measured during the seedling development stage as defined by the PO, then you can use "seedling cotyledon color" (TO:0000750) as described above.  If not, we can make a new term that will encompass the trait you are trying to map.

**Comment by cmungall** [comment]
Use TermGenie for any trait that conforms to the attribute-entity pattern

Permanent URL (will be up shortly)
http://to.termgenie.org

Use this for now:
http://oven.lbl.gov:8080/to-termgenie/

**Comment by cooperl09** [comment]
Added new term using TermGenie:
[Term]
id: TO:TEMP-eqsimple00
name: plant embryo cotyledon color
def: "A embryo cotyledon morphology trait (TO:0000775) which is the color of a plant embryo cotyledon (PO:0025470)." []
synonym: "embryo cotyledon color trait" EXACT [GOC:TermGenie]
is_a: TO:0000326 {is_inferred="true"} ! leaf color
is_a: TO:0000775 {is_inferred="true"} ! embryo cotyledon morphology trait
intersection_of: PATO:0000014 ! color
intersection_of: inheres_in PO:0025470 ! embryo cotyledon
relationship: inheres_in PO:0025470 {is_inferred="true"} ! embryo cotyledon
created_by: cooperl
creation_date: 2015-11-20T01:01:34Z

TermGenie seems to be using an older version of the PO?

**Comment by cmungall** [comment]
Did you do the Review and Submit step? With your submitter hat on, the 
end result for you should be a TO ID

(with your gatekeeper hat, you can push it out the queue into the 
ontology)

It's using the official release version of the PO - see the metadata 
here http://obofoundry.github.io/ontology/po.html
https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/po.md

Were we going to get rid of po-release-files?

**Comment by cooperl09** [comment]
That links to an old version- 
http://obofoundry.github.io/ontology/po.html
format-version: 1.2
data-version: releases/2015-09-21
date: 26:07:2013 14:51
saved-by: cooperl
auto-generated-by: OBO-Edit 2.3-beta5

**Comment by cmungall** [comment]
Follow on here: https://github.com/Planteome/plant-ontology/issues/614

**Comment by austinmeier** [comment]
Created new term: embryo cotyledon color (TO:0000980): An embryo cotyledon morphology trait (TO:0000775) which is the color of the plant embryo cotyledon (PO:0025470).
added xref: PATO:0000014

**Comment by austinmeier** [comment]
added new exact def'n "plant embryo cotyledon colour"

**Comment by maxglycine** [comment]
Since the definition states that it is the "embryo cotyledon color”  does that mean that we need a “seedling cotyledon color” also?  This underscores the problem of putting a developmental state in the definition.  I am of the opinion that it should not because the trait is the trait regardless of developmental state (cotyledon color).  To express the developmental state, we should be able to state the following:

The trait = cotyledon color.
The developmental state = embryo or seedling.
The anatomical part = cotyledon (self explanatory in this instance)

Thus to fully describe a phenotype, we would need a triplet (trait, anatomical part, developmental state).  This will also solve the problem of having separate terms for the same trait at different developmental time points.

What I don’t know is whether this system can be “reasoned” over.




On Dec 1, 2015, at 4:56 PM, Austin Meier <notifications@github.com<mailto:notifications@github.com>> wrote:


added new exact def'n "plant embryo cotyledon colour"

—
Reply to this email directly or view it on GitHub<https://github.com/Planteome/plant-trait-ontology/issues/353#issuecomment-161123702>.

Rex Nelson
Computational Biologist
G329 Agronomy Hall
Iowa State University
Ames, IA 50011
nelsonrt@iastate.edu<mailto:nelsonrt@iastate.edu>
515-294-1297

"Time flies like an arrow. Fruit flies like a banana"

**Comment by cooperl09** [comment]
The reason we differentiate between the seedling cotyledon color and embryo cotyledon color is that these are separate plant structures in the PO.  
plant embryo cotyledon (PO:0025470) and seedling cotyledon (PO:0025471).  
Both these plant structures are defined in terms of the developmental stage they exist in, so the dev. stage does not need to be restated, it is inherent.

**Comment by cmungall** [comment]
This can indeed be reasoned over

The only decision is whether to pre-compose the term in TO, or to 
post-compose (use two fields at the time of annotation)

Provided the design pattern is the same, then the two representations 
would be inferred equivalent

     'cotyledon color' and happens_during some 'embryo stage'
