### ISSUE TITLE
Number of female and male flower term

### ISSUE THREAD

**Issue by aafolabi** [Planteome/plant-trait-ontology#356]
Distinct number of female and male flower term should be created. Flower count in cassava can either be female or male or a count irrespective of the class.

**Comment by austinmeier** [comment]
suggested new terms:

staminate flower number: a flower number (TO:0002736) which is the number of staminate flowers (PO:0025600).
synonym: male flower number

pistillate flower number: a flower number (TO:0002736) which is the number of pistillate flowers (PO:0025599). 
synonym: female flower number

**Comment by maxglycine** [comment]
Isn’t it supposed to be “ a flower number TRAIT (TO:0002736) which is the number of staminate flowers (PO:0025600) ???



On Nov 18, 2015, at 2:37 PM, Austin Meier <notifications@github.com<mailto:notifications@github.com>> wrote:


suggested new terms:

staminate flower number: a flower number (TO:0002736) which is the number of staminate flowers (PO:0025600).
synonym: male flower number

pistillate flower number: a flower number (TO:0002736) which is the number of pistillate flowers (PO:0025599).
synonym: female flower number

—
Reply to this email directly or view it on GitHub<https://github.com/Planteome/plant-trait-ontology/issues/356#issuecomment-157855669>.

Rex Nelson
Computational Biologist
G329 Agronomy Hall
Iowa State University
Ames, IA 50011
nelsonrt@iastate.edu<mailto:nelsonrt@iastate.edu>
515-294-1297

"Time flies like an arrow. Fruit flies like a banana"

**Comment by maxglycine** [comment]
Also, aren’t we supposed to use a PATO reference for “number”?   If so, would that be PATO:0001555 "has number of"


On Nov 18, 2015, at 2:42 PM, Rex Nelson <nelsonrt@iastate.edu<mailto:nelsonrt@iastate.edu>> wrote:

Isn’t it supposed to be “ a flower number TRAIT (TO:0002736) which is the number of staminate flowers (PO:0025600) ???



On Nov 18, 2015, at 2:37 PM, Austin Meier <notifications@github.com<mailto:notifications@github.com>> wrote:


suggested new terms:

staminate flower number: a flower number (TO:0002736) which is the number of staminate flowers (PO:0025600).
synonym: male flower number

pistillate flower number: a flower number (TO:0002736) which is the number of pistillate flowers (PO:0025599).
synonym: female flower number

—
Reply to this email directly or view it on GitHub<https://github.com/Planteome/plant-trait-ontology/issues/356#issuecomment-157855669>.

Rex Nelson
Computational Biologist
G329 Agronomy Hall
Iowa State University
Ames, IA 50011
nelsonrt@iastate.edu<mailto:nelsonrt@iastate.edu>
515-294-1297

"Time flies like an arrow. Fruit flies like a banana"





Rex Nelson
Computational Biologist
G329 Agronomy Hall
Iowa State University
Ames, IA 50011
nelsonrt@iastate.edu<mailto:nelsonrt@iastate.edu>
515-294-1297

"Time flies like an arrow. Fruit flies like a banana"

**Comment by ejohnson1** [comment]
added new term: staminate flower number trait (TO:0000986): A flower number trait (TO:0002736) which is the number of staminate flowers (PO:0025600).
added dbxrefs "PATO:0001555" and "TO_GIT:356"
added exact_synonym: male flower number trait

**Comment by ejohnson1** [comment]
added new term: pistillate flower number trait (TO:0000986): A flower number trait (TO:0002736) which is the number of pistillate flowers (PO:0025599).
added dbxrefs "PATO:0001555" and "TO_GIT:356"
added exact_synonym: male flower number trait

**Comment by cmungall** [comment]
id: PATO:0000070
name: amount
synonym: "count" EXACT []
synonym: "count in organism" RELATED []
synonym: "number" RELATED []
synonym: "presence" RELATED []
synonym: "presence or absence in organism" EXACT []
synonym: "quantitative" EXACT []
