### ISSUE TITLE
flower number  TO:0002736

### ISSUE THREAD

**Issue by cooperl09** [Planteome/plant-trait-ontology#358]
Propose revised name and definition:
Was: flower number  TO:0002736
Revised: flower number trait (TO:0002736)

Current definition:  A flower morphology trait (TO:0000499) which is the number of flowers (PO:0009046).
   
This term should be a reproductive shoot system morphology trait (TO:0000786) since it can apply to a flower or an inflorescence.  

Add Xref to PATO:0001555 "has number of" 

See discussion on #356

**Comment by ejohnson1** [comment]
revised: flower number (TO:0002736) to flower number trait (TO:0002736)
revised parent from flower morphology trait (TO:0000499) to reproductive shoot system morphology trait (TO:0000786)
