### ISSUE TITLE
TermGenie instance for Plant Trait Ontology

### ISSUE THREAD

**Issue by cooperl09** [Planteome/plant-trait-ontology#361]
@cmungall  has set up an instance of TermGenie for the Plant Trait Ontology.  I am copying the various comments here for clarity:
From #353 :
CM: Use TermGenie for any trait that conforms to the attribute-entity pattern
**Permanent URL (up now)    http://to.termgenie.org/**

Proposed workflow for new requesters (from CM):
- Sign up for a persona account (use the link above)
- Add a ticket to the TO tracker, include persona username, requesting TG permission. I will take care of these.

**Comment by cooperl09** [comment]
Added new term using TermGenie:
[Term]
id: TO:TEMP-eqsimple00
name: plant embryo cotyledon color
def: "A embryo cotyledon morphology trait (TO:0000775) which is the color of a plant embryo cotyledon (PO:0025470)." []
synonym: "embryo cotyledon color trait" EXACT [GOC:TermGenie]
is_a: TO:0000326 {is_inferred="true"} ! leaf color
is_a: TO:0000775 {is_inferred="true"} ! embryo cotyledon morphology trait
intersection_of: PATO:0000014 ! color
intersection_of: inheres_in PO:0025470 ! embryo cotyledon
relationship: inheres_in PO:0025470 {is_inferred="true"} ! embryo cotyledon
created_by: cooperl
creation_date: 2015-11-20T01:01:34Z

TermGenie seems to be using an older version of the PO?

**Comment by cooperl09** [comment]
Response from @cmungall from #353 
Did you do the Review and Submit step? 

With your submitter hat on, the end result for you should be a TO ID (with your gatekeeper hat, you can push it out the queue into the ontology) 

It's using the official release version of the PO - see the metadata here 
http://obofoundry.github.io/ontology/po.html 
https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/po.md

**Comment by cooperl09** [comment]
That links to an old version?     http://obofoundry.github.io/ontology/po.html

Header stanza from the po.obo file:

format-version: 1.2
data-version: releases/2015-09-21   *(not sure what this is, it is not the date of the last release)*
date: 26:07:2013 14:51
saved-by: cooperl
auto-generated-by: OBO-Edit 2.3-beta5

**Comment by austinmeier** [comment]
Here are some issues Ethan and I have come across so far:

def’n uses “associated with”
doesn’t insert the parent term in the def’n
pato quality “has number of” makes for strange names and def’ns
synonym generated is just the name currently.  Does not pull synonyms from the PO
Ethan couldn’t submit a term “user is not authorized to execute a commit”
Austin was also not authorized

**Comment by cmungall** [comment]
To authorize, I will need the exact email/ID you use with Persona (to sign up for a persona account, click login in TG and follow the instructions).

Then place the email in this ticket. If it isn't someone I recognize it's best if you or Lol vouches for them

**Comment by marieALaporte** [comment]
@cmungall this is my persona account : marieangelique.laporte

**Comment by cmungall** [comment]
I think the account is a full email address

**Comment by maxglycine** [comment]
I will sign on with “maxglycine”



On Nov 23, 2015, at 3:17 PM, Chris Mungall <notifications@github.com<mailto:notifications@github.com>> wrote:


To authorize, I will need the exact email/ID you use with Persona (to sign up for a persona account, click login in TG and follow the instructions).

Then place the email in this ticket. If it isn't someone I recognize it's best if you or Lol vouches for them

—
Reply to this email directly or view it on GitHub<https://github.com/Planteome/plant-trait-ontology/issues/361#issuecomment-159066989>.

Rex Nelson
Computational Biologist
G329 Agronomy Hall
Iowa State University
Ames, IA 50011
nelsonrt@iastate.edu<mailto:nelsonrt@iastate.edu>
515-294-1297

"Time flies like an arrow. Fruit flies like a banana"

**Comment by cmungall** [comment]
On 24 Nov 2015, at 11:51, Rex Nelson wrote:

> I will sign on with “maxglycine”

Your persona id will be an email address, I believe, so I will need the 
complete address - gmail?

**Comment by maxglycine** [comment]
maxglycine@gmail.com<mailto:maxglycine@gmail.com>


On Nov 24, 2015, at 1:54 PM, Chris Mungall <notifications@github.com<mailto:notifications@github.com>> wrote:


On 24 Nov 2015, at 11:51, Rex Nelson wrote:

> I will sign on with “maxglycine”

Your persona id will be an email address, I believe, so I will need the
complete address - gmail?

—
Reply to this email directly or view it on GitHub<https://github.com/Planteome/plant-trait-ontology/issues/361#issuecomment-159387221>.

Rex Nelson
Computational Biologist
G329 Agronomy Hall
Iowa State University
Ames, IA 50011
nelsonrt@iastate.edu<mailto:nelsonrt@iastate.edu>
515-294-1297

"Time flies like an arrow. Fruit flies like a banana"

**Comment by cooperl09** [comment]
Created another test term today, here is the response:

Hello,
this is a confirmation that the following terms have been submitted for review in TermGenie:

[Term]
id: TO:1000000
name: stem internode bent
def: "A trait which is associated with the bent of a stem internode." [GOC:TermGenie]
synonym: "internodo del tallo (Spanish) bent" EXACT [GOC:TermGenie]
synonym: "??? (Japanese) bent" EXACT [GOC:TermGenie]
is_a: PATO:0000617 {is_inferred="true"} ! bent
is_a: TO:0000756 {is_inferred="true"} ! stem internode morphology trait
intersection_of: PATO:0000617 ! bent
intersection_of: inheres_in PO:0020142 ! stem internode
relationship: inheres_in PO:0020142 {is_inferred="true"} ! stem internode
created_by: cooperl
creation_date: 2015-11-24T22:16:25Z


Issues: 
* id: TO:1000000- id was generated, but it is incorrect
* I put in my TO:cooperl in the dbxref, but it is displaying  [GOC:TermGenie] instead.
* Template needs to be modified to removed the "associated with" phrase which we no longer use in the TO
* We do not need the Spanish and Japanese translations and these are not working anyway. Can eliminate? Looks like it is pulling from the PO.
*  Template needs to be modified so the starts with the genus (parent) term.
* I still am not getting these notifications- how do I get my "gatekeeper hat"?

**Comment by cmungall** [comment]
>    id: TO:1000000- id was generated, but it is incorrect

This is what I put in the to-idranges file for TG (TG always gets its own ID range, it's never the ID range of the submitter). We can change this if you like but this is a TG convention, it's meaningless anyway

>    I put in my TO:cooperl in the dbxref, but it is displaying [GOC:TermGenie] instead.

hmm, sounds like a bug

>    Template needs to be modified to removed the "associated with" phrase which we no longer use in the TO

Can you specify the template?

>    We do not need the Spanish and Japanese translations and these are not working anyway. Can eliminate? Looks like it is pulling from the PO.

We can't eliminate this automatically as PO is not using the correct language tags, so a machine has no reliable way of knowing which language a synonym is in.

>    Template needs to be modified so the starts with the genus (parent) term.

You mean the text def? It does look weird, but the assumption is that this is used for traits not phenotypes. If we want phenotypes we should have a different template.

In the interim you can override the text def.

>    I still am not getting these notifications- how do I get my "gatekeeper hat"?

Did you click the box to receive notifications?

I'm not sure if an email gets sent out to gatekeepers - @hdietze can confirm. In GO there is a rota and people check at the end of the day or when prodded.

You can get to the review page here:
http://to.termgenie.org/TermGenieReview.html

**Comment by hdietze** [comment]
**Missing Xref**
That is a bug, this will be fixed very soon (see https://github.com/geneontology/termgenie/commit/be2eefcc2df58e0d30b45408452b9e4481221fe6)

**GOC:TermGenie**
This can now be changed on the application level. If there is a TO specific xref to use, we can now change it.

**Notification E-mails**
E-mails are only send on one/two point(s) during the whole TermGenie process:
 * If the checkbox is set, after submitting a request to the queue
 * Once the Gatekeeper has committed the request to the editors file

The e-mail is only send to the original requester. There is no e-mail send to anyone else at any stage, there is no notification that a request has been added to the queue for review.
