### ISSUE TITLE
TO includes equivalence axioms on PATO 3-D shape which is causing build failures

### ISSUE THREAD

**Issue by cmungall** [Planteome/plant-trait-ontology#369]
see screenshot:

<img width="1416" alt="screen shot 2015-12-10 at 7 29 40 am" src="https://cloud.githubusercontent.com/assets/50745/11708472/ef910430-9f0f-11e5-8234-12a232e8fabb.png">

I noticed this because I saw the travis indicator on https://github.com/Planteome/plant-trait-ontology indicates the build is failing. That's the thing that looks like this:

[![Build Status](https://travis-ci.org/Planteome/plant-trait-ontology.svg?branch=master)](https://travis-ci.org/Planteome/plant-trait-ontology)

If you click on it it takes you here:
https://travis-ci.org/Planteome/plant-trait-ontology/builds/95929557

Travis is running the release pipeline which includes healthchecks such as ensuring no two classes are inferred equivalent. Usually best to scroll to the end of the report.
In this case:

EquivalentClasses(PATO:0002266 '3-D shape' TO:1000000 'stem internode bent' )

Using the Explanation feature of Protege will lead you to the right place.

As a general rule you should never add axioms to an imported class. Note that it can be easy to slip up in Protege and add axioms to the wrong class.

**Comment by cooperl09** [comment]
Right, fixed.
