### ISSUE TITLE
Avoid use of UnionOf whilst your source file is obo

### ISSUE THREAD

**Issue by cmungall** [Planteome/plant-trait-ontology#370]
TO recently included an equiv axiom that uses an OR

I recommend not using these:

 * Elk does not see these
 * Roundtripping in obo format occurs through the header of the file
 * In general unions indicate a bad smell. In this case the axiom doesn't buy you much

**Comment by cooperl09** [comment]
Ok, if I remove it, then the whole plant trait ontology no longer shows up in the tree as a pato quality.
Can you suggest another way to deal with this?  

We cannot use:
"quality  and ('occurs in' some 'whole plant')"
as that excludes the rest of the entities

This captures the scope of the ontology:
quality  and  ('occurs in' some 
    (molecular_function or cellular_component or biological_process or 'plant structure development stage' or 'plant anatomical entity'))
