### ISSUE TITLE
gibberellin biosynthesis trait (TO:0000992)

### ISSUE THREAD

**Issue by ejohnson1** [Planteome/plant-trait-ontology#383]
A biological process related trait (TO:0000283) which is a quality of the gibberellin biosynthetic process (GO:0009686). 

Synonyms: physiological process related trait, gibberellin biosynthesis

Defective (PATO:0000460)............Gibberellic acid (CHEBI:28833)

**Comment by ejohnson1** [comment]
revised def'n of gibberellin biosynthesis trait (TO:0000992) : A biological process trait (TO:0000283) which is a quality of a gibberellin biosynthetic process (GO:0009686).
revised comment: refers to gibberellic acid (CHEBI:28833)
removed broad_synonym: physiological process related trait

**Comment by cooperl09** [comment]
Please refer to the term gibberellin (CHEBI:24250), rather than gibberellin A3 (CHEBI:28833).

**Comment by ejohnson1** [comment]
Term: gibberellin biosynthesis trait (TO:0000992) 

Def'n: A biological process trait (TO:0000283) which is a quality of a gibberellin biosynthetic process (GO:0009686).

Comment: Refers to gibberellin (CHEBI:24250)
