### ISSUE TITLE
cellulose content  (TO:0000993)

### ISSUE THREAD

**Issue by ejohnson1** [Planteome/plant-trait-ontology#384]
Def'n: A metabolite content trait (TO:0000281) which is the quality of the cellulose content in a plant or plant part (TO:0000993)

comment: refers to cellulose (CHEBI:17057)

Revised def'n: A metabolite content trait (TO:0000281) which is the quality of the cellulose content in a plant structure (PO:0009011).

**Comment by ejohnson1** [comment]
added dbxref: TO_GIT:384

**Comment by cooperl09** [comment]
Suggested revision:  cellulose content (TO:0000993):
A metabolite content trait (TO:0000281) which is the amount of cellulose (CHEBI:62968) in a plant structure (PO:0009011).

Comment: Refers to crystalline cellulose (CHEBI:62968): A (1→4)-β-D-glucan (cellulose) in crystalline form with a structure consisting of several hundred to over ten thousand D-glucose residues joined by β(1→4) glycosidic linkages.

Note the CHEBI term above is incorrect:  
CHEBI:17057 is cellobiose: A glycosylglucose consisting of two glucose units linked via a β(1→4) bond.

**Comment by ejohnson1** [comment]
Term: cellulose content (TO:0000993)

Definition: A carbohydrate content trait (TO:0000291) which is the amount of cellulose (CHEBI:62968) in a plant structure (PO:0009011).

Comment: Refers to crystalline cellulose (CHEBI:62968): A (1→4)-β-D-glucan (cellulose) in crystalline form with a structure consisting of several hundred to over ten thousand D-glucose residues joined by β(1→4) glycosidic linkages.
