### ISSUE TITLE
anther morphology trait ( TO:1000022) and child terms

### ISSUE THREAD

**Issue by austinmeier** [Planteome/plant-trait-ontology#385]
Suggested name:  anther morphology trait
suggested def'n: A collective plant organ structure morphology trait (TO:0000842) which is a quality of an anther (PO:0009066).

suggested children:  
anther color (TO:0000187)
anther length (TO:0000531)
anther shape (TO:0000214)

**Comment by austinmeier** [comment]
name: anther morphology trait TO:1000022
def: "A collective plant organ structure trait (TO:0000842) which is the quality of an anther (PO:0009066)." [TO:meiera]
is_a: TO:0000842 ! collective plant organ structure morphology trait
intersection_of: PATO:0001241 ! physical object quality
intersection_of: inheres_in PO:0009066 ! anther

**Comment by ejohnson1** [comment]
Revised def'n of Anther Length (TO:0000531): An anther morphology trait (TO:1000022) which is the length of the anther (PO:0009066).
Added comment: Refers to length (PATO:0000122)

Revised def'n of Anther Shape (TO:0000214): An anther morphology trait (TO:1000022) which is the shape of an anther (PO:0009066).
Added comment: Refers to shape (PATO:0000052)

moved term: plant ovary color (TO:1000016) to "is_a" plant ovary morphology (TO:1000012)

Added dbx ref: "TO_GIT:385" to anther color (TO:0000187), anther shape (TO:0000214), and anther morphology trait (TO:1000022)

**Comment by ejohnson1** [comment]
Revised def'n of anther length (TO:0000531): An anther morphology trait (TO:1000022) which is the length (PATO:0000122) of an anther (PO:0009066).

Revised def'n of anther shape (TO:0000214): An anther morphology trait (TO:1000022) which is the shape (PATO:0000052) of an anther (PO:0009066).

Revised def'n of anther color (TO:0000187): An anther morphology trait (TO:1000022) which is the color (PATO:0000014) of an anther (PO:0009066).
