### ISSUE TITLE
anther number (TO:0000210) vs. stamen number (TO:0000225)

### ISSUE THREAD

**Issue by austinmeier** [Planteome/plant-trait-ontology#387]
Is there a need for the term 'anther number' (TO:0000210)?? 
Suggest merging with term 'stamen number' (TO:0000225).

suggest maintaining if it is possible to have multiple anthers on a single stamen, or if this trait is describing the presence/absence of anthers on stamen, in which case it could be renamed 'anther presence'.

**Comment by cooperl09** [comment]
This is an odd trait as it is defined as:
anther number (TO:0000210): Variation in the number of anthers in androecium. Source: GR:pj 

There is no QTL data with that name at Gramene: [http://archive.gramene.org/qtl/)](http://archive.gramene.org/qtl/)
And no associations to it in our database: [http://browser.planteome.org/amigo/term/TO:0000210](http://browser.planteome.org/amigo/term/TO:0000210)

Propose revising the def'n for clarity and adding a synonym "anther presence" 
proposed new name and def'n: 
anther number (TO:0000210): A stamen morphology trait (TO:0000215) which is the number of anthers (PO:0009066) in a stamen (PO:0009029).

Another way this could be modeled is revising name to be "anther presence", as described above.

**Comment by cooperl09** [comment]
Revised def'n of anther number (TO:0000210): def: "A stamen morphology trait (TO:0000215) which is the number of anthers (PO:0009066) in a stamen (PO:0009029)."

updated EA: 'has number of'
 and ('inheres in' some anther) and ('occurs in' some stamen)
