### ISSUE TITLE
Mineral ion content traits from McCouch Lab

### ISSUE THREAD

**Issue by jaiswalp** [Planteome/plant-trait-ontology#412]
I just received a request to add the following traits from the Cornell group.

root hair density
root cortex area
root stele area
root aerenchyma area
number of metaxylem vessels
days to booting
panicle terminal primary branch length
panicle internode length
rachis thickness
number of panicle internodes
number of panicle branches per internode
horizontal width of the root system
root Al content
root As content
root B content
root Ba content
root Ca content
root Cd content
root Co content
root Cr content
root Cu content
root Fe content
root I content
root K content
root Li content
root Mg content
root Mn content
root Mo content
root Na content
root Ni content
root P content
root Pb content
root Rb content
root S content
root Se content
root Si content
root Sr content
shoot Zn content
shoot Al content
shoot As content
shoot B content
shoot Ba content
shoot Ca content
shoot Cd content
shoot Co content
shoot Cr content
shoot Cu content
shoot Fe content
shoot I content
shoot Li content
shoot Mg content
shoot Mn content
shoot Mo content
shoot Ni content
shoot Pb content
shoot Rb content
shoot S content
shoot Se content
shoot Si content
shoot Sr content
shoot Zn content

**Comment by marieALaporte** [comment]
Most of the traits listed should be pretty straightforward to add with the DP approach.

**Comment by austinmeier** [comment]
An excellent opportunity to try out the new "term genie replacement"?

**Comment by jaiswalp** [comment]
Suggested descriptions from the McCouch lab:

root hair density-->number of root hairs per root surface area
root cortex area-->cross-sectional area of the root cortex
root stele area-->cross-sectional area of the root stele
root aerenchyma area-->cross-sectional area of the root aerenchyma
number of metaxylem vessels-->number or metaxylem vessels in a cross section
days to booting-->Number of days after transplanting when ~50% of plants from a plot replicate reach booting stage (visible flag leaf)
panicle terminal primary branch length-->the length of the terminal primary branch on a panicle
panicle internode length-->The distance between two nodes
rachis thickness-->the diameter of the rachis
number of panicle internodes-->the number of nodes in a panicle
number of panicle branches per internode-->the average number of branches per node for all nodes within a panicle.
horizontal width of the root system-->Maximum horizontal width of the whole root system
root? and shoot ion
content-->µg of ion/gram of dry weight plant tissue

**Comment by jaiswalp** [comment]
@austinmeier @marieALaporte go for it. How soon we can get these in.

**Comment by cooperl09** [comment]
The shoot-related terms will need be be shoot axis XYZ, as shoot is not a PO term.  Their form can be added as a synonym.

**Comment by austinmeier** [comment]
@cooperl09 can we use shoot system (PO:0009006)?

**Comment by marieALaporte** [comment]
@jaiswalp The definitions will be created automatically by the tool. But according to the descriptions you gave, maybe the names of the traits will need to be slightly different (e.g. maximal width)

**Comment by cooperl09** [comment]
@austinmeier the shoot system PO:0009006 is the entire axial structure of the plant- I don't think it is appropriate here.

**Comment by jaiswalp** [comment]
sure. keep the original names as synonyms

**Comment by elsadebecker** [comment]
Hi, I'm the one that requested these terms. Such quick turnaround, wow!
There are already a couple "shoot __ content" traits, for example TO:0020004, TO:0020114, and TO:0020003. As far as I can tell they don't refer to any specific shoot PO term yet.

**Comment by austinmeier** [comment]
@elsadebecker When you are measuring the "shoot x content" are you using the entire portion of the plant that is above ground?

**Comment by cooperl09** [comment]
TO:0020004, TO:0020114, and TO:0020003 are legacy terms  and need to be fixed...

**Comment by elsadebecker** [comment]
@austinmeier yes, everything above ground was analyzed as shoot and everything below ground was analyzed as root

**Comment by austinmeier** [comment]
Excellent.  I believe shoot system (PO:0009006) is appropriate in this case.

**Comment by cooperl09** [comment]
in that case they should be shoot system and root system. Thanks for clarifying

**Comment by elsadebecker** [comment]
Also, all panicle traits are from [Genome-wide association and high-resolution phenotyping link Oryza sativa panicle traits to numerous trait-specific QTL clusters, Crowell et al., 2016](https://www.nature.com/articles/ncomms10527#supplementary-information), and I took the descriptions from page 116 of the [supplementary information pdf](https://www.nature.com/article-assets/npg/ncomms/2016/160204/ncomms10527/extref/ncomms10527-s1.pdf)

**Comment by marieALaporte** [comment]
@elsadebecker the shoot Zn content appears twice in the list. I suppose one should be changed to root Zn content, correct?

**Comment by elsadebecker** [comment]
Yes, thanks!

**Comment by cooperl09** [comment]
Is there supposed to be a 'shoot (system) potassium K content trait? Appears all the rest are done in both.

**Comment by elsadebecker** [comment]
I didn't request it because there was already TO:0020003, shoot potassium content

**Comment by cooperl09** [comment]
All the mineral content terms have been created, and will be available on our dev browser (http://dev.planteome.org/amigo) later today.

TO:1000025 | root system aluminum content
TO:1000026 | root system arsenic content
TO:1000027 | root system boron content
TO:1000028 | root system barium content
TO:1000029 | root system calcium content
TO:1000030 | root system cadmium content
TO:1000031 | root system cobalt content
TO:1000032 | root system chromium content
TO:1000033 | root system copper content
TO:1000034 | root system iron content
TO:1000035 | root system iodine content
TO:1000036 | root system potassium content
TO:1000037 | root system lithium content
TO:1000038 | root system magnesium content
TO:1000039 | root system manganese content
TO:1000040 | root system molybdenum content
TO:1000041 | root system sodium content
TO:1000042 | root system nickel content
TO:1000043 | root system phosphorus content
TO:1000044 | root system lead content
TO:1000045 | root system rubidium content
TO:1000046 | root system sulfur content
TO:1000047 | root system selenium content
TO:1000048 | root system silicon content
TO:1000049 | root system strontium content
TO:1000050 | root system zinc content
  |  
TO:1000051 | shoot system aluminium content
TO:1000052 | shoot system arsenic content
TO:1000053 | shoot system boron content
TO:1000054 | shoot system barium content
TO:1000055 | shoot system calcium content
TO:1000056 | shoot system cadmium content
TO:1000057 | shoot system cobalt content
TO:1000058 | shoot system chromium content
TO:1000059 | shoot system copper content
TO:1000060 | shoot system iron content
TO:1000061 | shoot system iodine content
TO:1000062 | shoot system lithium content
TO:1000063 | shoot system magnesium content
TO:1000064 | shoot system manganese content
TO:1000065 | shoot system molybdenum content
TO:1000066 | shoot system nickel content
TO:1000067 | shoot system lead content
TO:1000068 | shoot system rubidium content
TO:1000069 | shoot system sulfur content
TO:1000070 | shoot system selenium content
TO:1000071 | shoot system silicon content
TO:1000072 | shoot system strontium content
TO:1000073 | shoot system zinc content

**Comment by cooperl09** [comment]
panicle trait requests have been moved to : #419

**Comment by cooperl09** [comment]
root relate traits have been moved to #417

**Comment by elsadebecker** [comment]
These are all from chapter 3 of the dissertation [Combining next-generation phenotyping and genome-wide association analysis to explore the genetic architecture of nutrient acquisition in domesticated Asian rice (Oryza sativa L.).](https://search.proquest.com/docview/1426182399/fulltextPDF/8379F05C67914405PQ/1?accountid=10267)

**Comment by cooperl09** [comment]
That link goes to a Cornell University web login page....
Cannot access it from here

**Comment by elsadebecker** [comment]
No, there was never a paper published. Try [this link](https://search.proquest.com/docview/1426182399)  instead? The proquest ID is 1426182399, if that helps.

**Comment by elsadebecker** [comment]
days to booting moved to #420

**Comment by elsadebecker** [comment]
number of metaxylem vessels moved to #421

**Comment by cooperl09** [comment]
Based on our meeting today, these have been completed, so I am closing this issue.
