### ISSUE TITLE
request for more TOs

### ISSUE THREAD

**Issue by elsadebecker** [Planteome/plant-trait-ontology#415]
I modeled the definitions on what should end up as sibling TOs.

1. Flag leaf area: A flag leaf anatomy and morphology trait (TO:0000832) which is associated with the area of the flag leaf (PO:0020103).
 
2. Polished grain length to width ratio: A grain length to width ratio (TO:0002731) which is determined from grain length and grain width on dehulled polished rice grain
 
3. Polished grain length: A grain length (TO:0000734) monitored after dehulling and polishing
 
4. Polished grain width: A grain width (TO:0000975) which is the width of the polished dehulled grain

**Comment by cooperl09** [comment]
Here are the new trait terms as requested:

[Term]
id: TO:0000996
name: flag leaf area
namespace: plant-trait-ontology
def: "A flag leaf anatomy and morphology trait (TO:0000832) which is the area of the flag leaf (PO:0020103)." [PMID:26841834]
creation_date: 2017-07-10

[Term]
id: TO:0000997
name: polished grain length
namespace: plant-trait-ontology
def: "A grain length (TO:0000734) measured on a dehulled, polished grain." [PMID:26841834] 
synonym: "white rice grain length (narrow)" NARROW []
creation_date: 2017-07-10

[Term]
id: TO:0000998
name: polished grain width
namespace: plant-trait-ontology
def: "A grain width (TO:0000975) which is the width of the dehulled, polished grain." [PMID:26841834]
synonym: "white rice grain width (narrow)" NARROW []
creation_date: 2017-07-10

[Term]
id: TO:0000999
name: polished grain length to width ratio
namespace: plant-trait-ontology
def: "A grain length to width ratio (TO:0002731) measured on a dehulled, polished grain." [PMID:26841834] 
synonym: "white rice grain length to width ratio (narrow)" NARROW []
creation_date: 2017-07-10

**Comment by elsadebecker** [comment]
Perfect! Thanks
