### ISSUE TITLE
root-related TO requests

### ISSUE THREAD

**Issue by elsadebecker** [Planteome/plant-trait-ontology#417]
A few more root-related traits:
- root cross sectional area: the cross sectional area of a root
- root system width to depth ratio: ratio of root system width (requested below) to root system depth 
- horizontal width of the root system-->Maximum horizontal width of the whole root system
root
- root hair density-->number of root hairs per root surface area
- root cortex area-->cross-sectional area of the root cortex
- root stele area-->cross-sectional area of the root stele
- root aerenchyma area-->cross-sectional area of the root aerenchyma

Let me know if I should provide more information to make creating the terms easier
Thanks!

**Comment by elsadebecker** [comment]
from chapter 3 and 4 of the dissertation [NUTRITIONAL AND GENETIC ARCHITECTURE OF ROOT TRAITS IN RICE](https://etda.libraries.psu.edu/files/final_submissions/9742)

**Comment by elsadebecker** [comment]
This was overly confusing, sorry. Root cross sectional area, root hair density, root cortex area, root stele area, and root aerenchyma area are all from the dissertation I linked above. 
width of the root system and root system width to depth ratio are both from PMID: 21454799

**Comment by cooperl09** [comment]
I have created the following terms, for this request.  Please review on the 

root hair density | TO:0001051
root cortex cross-sectional area | TO:0001052
root stele cross-sectional area | TO:0001054
root aerenchyma cross-sectional area | TO:0001055
root cross sectional area | TO:0001056
root system width | TO:0001057 
root system depth | TO:0001058
root system width to depth ratio | TO:0001059

**Comment by elsadebecker** [comment]
Thanks! One thing is root system depth and root system width to depth ratio both lack PMID links (PMID: 21454799)

**Comment by cooperl09** [comment]
Thanks for catching those- they have been added.
