### ISSUE TITLE
Relative/Comparative growth rate TO request

### ISSUE THREAD

**Issue by elsadebecker** [Planteome/plant-trait-ontology#418]
comparative growth rate: growth over a period of time compared to total size (would be better called relative growth rate, but that is taken by TO:0000515)

**Comment by cooperl09** [comment]
Please use the existing term: relative growth rate (TO:0000515) for these data.
After reviewing the paper above and other references I revised the existing definition of relative growth rate (TO:0000515): 
Revised def'n: A vigor trait (TO:0000250) that is the increase in aboveground biomass in a defined period of time.
Added New comment: Relative growth rate may be calculated in various ways, usually as a rate of growth compared to the amount of starting biomass. In some cases, it may be expressed as a percentage.
This fits the definition in the literature, as well as the used in the paper above and in the QTL study.

**Comment by elsadebecker** [comment]
Thanks, this works really well!

**Comment by cooperl09** [comment]
Reminder to update the number in your database for relative growth rate (TO:0000515)
