### ISSUE TITLE
number of metaxylem vessels TO request

### ISSUE THREAD

**Issue by elsadebecker** [Planteome/plant-trait-ontology#421]
number of metaxylem vessels: number of metaxylem vessels in a cross section

**Comment by elsadebecker** [comment]
also from chapter 3 and 4 of the dissertation [NUTRITIONAL AND GENETIC ARCHITECTURE OF ROOT TRAITS IN RICE](https://etda.libraries.psu.edu/files/final_submissions/9742)

**Comment by cooperl09** [comment]
Term has been created, along with a new PO term for the metaxylem vessel (PO:0025620), 
See: https://github.com/Planteome/plant-ontology/issues/678

number of metaxylem vessels (TO:0001066):  A vascular tissue morphology trait (TO_0000470) which is the number of metaxylem vessels (PO:0025620).

Comment: The number of metaxylem vessels (PO:0025620) may be counted in a cross section of a primary xylem (PO:0005849).

Parent term is fairly general, we may want to make a more specific one later

**Comment by elsadebecker** [comment]
Thanks!
