### ISSUE TITLE
rice milling quality traits with unsatisfying definitions

### ISSUE THREAD

**Issue by elsadebecker** [Planteome/plant-trait-ontology#422]
The definitions of these terms both sound less like TOs and more like POs. Can they be rewritten as ratios/percents/yields, following [these IRRI definitions](http://www.knowledgebank.irri.org/index.php?option=com_zoo&task=item&item_id=1131&Itemid=822)?

- TO:0000222

 "head rice": The 3/4 or longer whole milled kernels separated from the total milled rice. Source: RiceCAP: http://www.uark.edu/ua/ricecap/glossary_ricecaplist.htm ->"head rice ratio/percent": the ratio/percent of milled rice grains that are at least 3/4 the length of a whole grain

- TO:0000144

 "milled rice": Rice kernels that have been milled to remove the bran, leaving "white" or milled rice. Source: RiceCAP http://www.uark.edu/ua/ricecap/glossary_ricecaplist.htm-> "milled rice yield": the weight of milled rice divided by the weight of the paddy sample

On the other hand, these are both very specific to rice, so it might make more sense to rewrite them as more general definitions

**Comment by cooperl09** [comment]
Revised these traits to be measures of grain yield, as suggested, as this fits the definitions in use better.

**Comment by elsadebecker** [comment]
Thanks!
