### ISSUE TITLE
Pulvinus size

### ISSUE THREAD

**Issue by sammyjava** [Planteome/plant-trait-ontology#429]
The cowpea folks at UC-Riverside have done experiments on Pulvinus size. I'd like a TO term for that! The corresponding PO term is PO:0009000.
Thanks!

**Comment by cooperl09** [comment]
We should be able to add that term, but it would be helpful to see the context for it as we actually have four pulvinus terms in PO:
 PO:0009000 pulvinus
                         [is_a relation] PO:0009017 inflorescence branch pulvinus
                         [is_a relation] PO:0008017 leaf sheath pulvinus
                         [is_a relation] PO:0009111 petiole pulvinus 
Do you know which type of pulvinus they are looking at?  If you could give us a link to a published paper, that would be helpful.

**Comment by sammyjava** [comment]
It's work done by Michael Schwartz at UC-Riverside with the UCR-minicore cowpea population, but not published yet. We're collaborators and will be loading those QTLs onto CowpeaMine. We can wait until it's published. The spreadsheet I have simply calls it "Pulvinus size." I think it's such a rare thing to study, a TO term simply called "Pulvinus size" linked to PO:0009000 would suffice.

**Comment by cooperl09** [comment]
Added new term for pulvinius size (TO:0001075): A cardinal organ part morphology trait (TO:0000754) which is the size of a pulvinus (PO:0009000).

**Comment by sammyjava** [comment]
Thanks!
