### ISSUE TITLE
RO:0002310 used and not defined anywhere

### ISSUE THREAD

**Issue by bradfordcondon** [Planteome/plant-trait-ontology#441]
Hello!

similar issue to #439 different terms.  Our EBI OLS fails searching for `RO:0002310`.  Several terms in `PECO` use the term, as defined here in `TO`.  However, if i check the `PECO` OBO, `RO:0002310` is not defined or used.

I can't figure out what this term is supposed to be or which ontology is supposed to contain it (although given the issues with the relationship ontology i'd bet its orphaned?")

Thank!

**Comment by bradfordcondon** [comment]
We're going to change our loader to throw warnings instead of errors.  After I do so I'll bea ble to provide you a full list of terms that could not be found on EBI...

**Comment by cooperl09** [comment]
I did a quick search and found RO:0002310 on the OLS: exposure event or process
https://www.ebi.ac.uk/ols/ontologies/ro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002310

I will look a bit deeper into the usage

**Comment by bradfordcondon** [comment]
oh great, i searched for RO:0002310 and didnt find it somehow, apologies.

I can also find it via the API If im smart and use hte case sensitive accesion RO instead of ro.  I'm not sure why our loader is failing but its not because this term isnt in EBI, apologies.

https://www.ebi.ac.uk/ols/api/ontologies/ro/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0002310
