### ISSUE TITLE
missing colon in dbxref of TO:0000030

### ISSUE THREAD

**Issue by easr** [Planteome/plant-trait-ontology#448]
In the following entry:

[Term]
id: TO:0000030
name: sedge weed
def: "A common sedge weed Cyperus iria (rice flatsedge), Cyperus difformis (Small flower umbrella sedge),  Rice field bulrush Scirpus mucronatus, River bulrush Scirpus fluviatilis. Grows as a weed in the rice field. Can be distinguished from grass plant by the leaf shape, venation, stem cross-section and plant shape leaf shape." [Gramene:pankaj_jaiswal, http//www.ipm.ucdavis.edu/PMG/r682700999.html, ISBN:9712200299]
is_a: TO:0000347 ! weed damage

one of the dbxrefs is http//www.ipm.ucdavis.edu/PMG/r682700999.html

it should be: http://www.ipm.ucdavis.edu/PMG/r682700999.htm

nevertheless, that URL points to a non existing page... could you fix it?

**Comment by cooperl09** [comment]
Thanks for catching this @easr - fixed in commit #1744d192cce6039eb196fcef11c0a9677423901c
Alos revised name, def'n and comment
