### ISSUE TITLE
New Term Request: Heterodera glycines resistance

### ISSUE THREAD

**Issue by ScottKalberer** [Planteome/plant-trait-ontology#461]
Hello, I request the creation of a new PTO term for _Heterodera glycines_ (Soybean cyst nematode) resistance.  The term would be a child of TO:0000384 nematode damage resistance.  There is an existing term for "Reaction to Heterodera glycines" at the SoyBase Soybean Trait Ontology (SOY:0001335), but one is needed for other hosts (e.g., _Phaseolus vulgaris_).

Definition could follow the pattern "Causal agent: Heterodera glycines.  Resistance of plant or plant part to damage caused by the pathogen Heterodera glycines (Soybean cyst nematode)."  The race does not need to be specified.  Thank you.

**Comment by cooperl09** [comment]
Hi @ScottKalberer 
Term has been created: 
id: TO:0001111
name: Heterodera glycines response
def: "A nematode damage response (TO:0000384) to the Soybean cyst nematode (Heterodera glycines)." [TO:cooperl]
comment: Refers to soybean cyst nematode (Heterodera glycines; NCBITaxon:51029).
xref: TO_GIT:461
is_a: TO:0000384 ! nematode damage resistance
created_by: cooperl 

The new term will be available on our development browser tomorrow: https://dev.planteome.org/amigo

**Comment by ScottKalberer** [comment]
Thank you Laurel for creation of the Heterodera glycines term.
