### ISSUE TITLE
New Term Request: Fusarium solani resistance

### ISSUE THREAD

**Issue by ScottKalberer** [Planteome/plant-trait-ontology#466]
Hello, I would like a new PTO term for Fusarium solani resistance that may be applied to any plant species or disease syndrome (although I am currently working on Fusarium root rot in Phaseolus vulgaris).  The term would be a child of fungal disease resistance (TO:0000439). There are existing terms for "Reaction to Fusarium solani infection" at the SoyBase Soybean Trait Ontology (SOY:0001456), and for Common bean at the Crop Ontology.  The Crop Ontology terms are over-specified as Fusarium solani in field (CO_335:0000025) and Fusarium solani in greenhouse (CO_335:0000026).

I believe the teleomorph (sexual reproductive stage) of Fusarium solani is known as Nectria haematococca var. brevicona.

**Comment by cooperl09** [comment]
Fusarium solani disease response (TO:0001147) has been added, child of Ascomycete fungal disease response trait (TO:0001145). 
You can view it on our development browser.  Will be available on OLS etc once we do a release.
https://dev.planteome.org/amigo/term/TO:0001147
