### ISSUE TITLE
NTR: plant fruit legume number

### ISSUE THREAD

**Issue by celineaubert** [Planteome/plant-trait-ontology#493]
Def: A fruit number trait (TO:0000894) which is the number of legume fruits (PO:0030100) per whole plant (PO:0000003).

Ref: https://cropontology.org/rdf/CO_340:0000356

Exact syn: Number of pods per plant

Hierarchy: TO:0000894 fruit number trait

ORCID: [0000-0001-9832-772X](https://orcid.org/0000-0001-9832-772X)

**Comment by cooperl09** [comment]
Added new term:
id: TO:0001125
name: pod number trait
def: "A fruit number trait (TO:0000894) which is the number of legume fruits (PO:0030100), or pods." [TO:cooperl]
synonym: "legume fruit number (exact)" EXACT []
is_a: TO:0000894 ! fruit number trait
