### ISSUE TITLE
NTR:legume fruit yield

### ISSUE THREAD

**Issue by celineaubert** [Planteome/plant-trait-ontology#495]
Def: A fruit yield trait (TO:0000871) which is the weight of legume fruit (PO:0030100) per unit area.

Ref: DOI:[10.7176/JBAH/12-22-02](http://dx.doi.org/10.7176/JBAH/12-22-02)

Exact syn: Pod yield

Hierarchy: TO:0000871 fruit yield trait

ORCID: https://orcid.org/0000-0001-6284-4821

**Comment by cooperl09** [comment]
New term has been created:
id: TO:0001142
name: legume fruit yield trait
def: "A fruit yield trait (TO:0000871) which is the amount of legume fruit (PO:0030100) produced." [PO:0030100, TO:Laurel_Cooper]
comment: The yield of pods or legume fruits is often measured in weight per unit area of land.
synonym: "pod yield (exact)" EXACT []
xref: TO_GIT:495
is_a: TO:0000871 ! fruit yield trait
created_by: https://orcid.org/0000-0002-6379-8932
creation_date: 2023-07-17T17:24:36Z
