### ISSUE TITLE
NTR: capsule fruit length

### ISSUE THREAD

**Issue by celineaubert** [Planteome/plant-trait-ontology#497]
Def: A capsule fruit morphology trait (TO:0001078) which is the length of a capsule fruit (PO:0030091). It is measured from the bottom to the top of the seed chamber outside. 

Ref: DOI: 10.1007/978-3-319-98098-0_2

Exact syn: capsule length

SubClassof: TO:0001078 capsule fruit morphology trait

ORCID: [0000-0001-9832-772X](https://orcid.org/0000-0001-9832-772X)

**Comment by cooperl09** [comment]
capsule fruit length (TO:0001132): A capsule fruit morphology trait (TO:0001078) which is the length  (PATO:0000921) of a capsule fruit (PO:0030091).
- synonym: capsule length (exact)
