### ISSUE TITLE
NTR: capsule fruit width

### ISSUE THREAD

**Issue by celineaubert** [Planteome/plant-trait-ontology#498]
Def: A capsule fruit morphology trait (TO:0001078) which is the width of a fruit capsule (PO:0030091). It is measured from the edge of a carpel (PO:0009030) to the edge of the other carpel.

Ref: DOI: 10.1007/978-3-319-98098-0_2

Exact syn: capsule width

SubClassof: TO:0001078 capsule fruit morphology trait

ORCID: [0000-0001-9832-772X](https://orcid.org/0000-0001-9832-772X)

**Comment by cooperl09** [comment]
*capsule fruit width (TO:0001131): A capsule fruit morphology trait (TO:0001078) which is the width (PATO:0000921) of a capsule fruit (PO:0030091).
- synonym: capsule width (exact)
