### ISSUE TITLE
NTR: capsule fruit thickness

### ISSUE THREAD

**Issue by celineaubert** [Planteome/plant-trait-ontology#499]
Def: A capsule fruit morphology trait (TO:0001078) which is the thickness of a fruit capsule (PO:0030091). It is measured across the carpel (PO:0009030).

Ref: DOI: 10.1007/978-3-319-98098-0_2

Exact syn: capsule thickness

SubClassof: TO:0001078 capsule fruit morphology trait

ORCID: [0000-0001-9832-772X](https://orcid.org/0000-0001-9832-772X)

**Comment by cooperl09** [comment]
* capsule fruit thickness (TO:0001133): A capsule fruit morphology trait (TO:0001078) which is the thickness (PATO:0000915) of a capsule fruit (PO:0030091).
- synonym: capsule thickness (exact)
