### ISSUE TITLE
NTR: capsule fruit number

### ISSUE THREAD

**Issue by celineaubert** [Planteome/plant-trait-ontology#500]
Def: A plant morphology trait (TO:0000017 ) which is the number of capsules (PO:0030091) per whole plant (PO:0000003).

Ref: DOI: 10.1007/978-3-319-98098-0_2

Exact syn: number of capsules per plant

SubClassof: TO:0001078 capsule fruit morphology trait

ORCID: [0000-0001-9832-772X](https://orcid.org/0000-0001-9832-772X)

**Comment by cooperl09** [comment]
capsule fruit number TO:0001135: -  A fruit number trait (TO:0000894) which is the number of capsule fruit (PO:0030091).
