### ISSUE TITLE
capsule fruit seed number- child of fruit seed number (TO:0000445)

### ISSUE THREAD

**Issue by celineaubert** [Planteome/plant-trait-ontology#501]
Def: A capsule fruit morphology trait (TO:0001078) which is the mean number of seeds (PO:0009010) per capsule (PO:0030091) that are  randomly selected.

Could you please add the following terms synonyms of the trait TO:0000445 fruit seed number?
- capsule seed number
- seeds per capsule

**Comment by celineaubert** [comment]
sorry, added this issue twice #494

**Comment by cooperl09** [comment]
capsule seed number TO:0001134: A fruit seed number (TO:0000445) which is the number of seeds in a capsule fruit (PO:0030091).
TO_GIT:501
- synonym:  seeds per capsule (exact)
