### ISSUE TITLE
Onion bulb traits

### ISSUE THREAD

**Issue by austinmeier** [Planteome/plant-trait-ontology#503]
Hi guys, it's me!
We are working to map our vegetable breeding traits to the trait ontology, and I've begun looking at onion traits.  As you can predict: lots of the information breeders are interested in is related to the onion itself.  I found [this source from NYBG](https://libguides.nybg.org/c.php?g=654974&p=4710781) letting me know that onion bulbs are in fact -stems.  So I was thinking there might be a need for new parent term "Bulb morphology trait" somewhere under "stem morphology trait" (TO:0000361).

Proposed definition: "A stem morphology trait (TO:0000361) which is the quality of a bulb (PO:0025356).

**Comment by cooperl09** [comment]
Hi Austin,
An onion bulb is actually a compressed shoot system (which includes a stem).
A short, enlarged shoot system (PO:0009006) that has as parts a short stem (PO:0009047) in which the shoot internodes (PO:0005005) do not elongate, and one or more buds (PO:0000055) enclosed by fleshy leaves (PO:0009025) or leaf bases (PO:0020040). Source: [ISBN:9780881928501]
So I suggest: 
bulb morphology trait: A shoot system morphology trait (TO:0000077) which is a quality of a bulb (PO:0025356).
I actually have a couple of other bulb trait requests I am currently working on: bulb diameter, bulb height, bulb width.
Are there others you are interested in?

**Comment by austinmeier** [comment]
Good thing I asked!  That definition looks perfect. 
We will for sure be interested in those you mentioned, and bulb color for sure.  I'm not done going through all our onion traits, so I can't comment on any others we may need, but I'll keep you in the loop!

Thanks, lol

**Comment by cooperl09** [comment]
Bulb morphology traits have been created and are available on the Planteome Development browser at: https://dev.planteome.org/amigo and they will be included in the new full release of the TO.
- bulb morphology trait (TO:0001126):  A shoot system morphology trait (TO:0000077) which is a quality of a bulb (PO:0025356).
- - bulb diameter TO:0001127: A bulb morphology trait (TO:0001126) which is the diameter (PATO:0001334) of a bulb (PO:0025356).
- - bulb height TO:0001128:  A bulb morphology trait (TO:0001126) which is the height (PATO:0000119) of a bulb (PO:0025356).
synonym: Bulb vertical diameter, exact
- - bulb width TO:0001129: A bulb morphology trait (TO:0001126) which is the width (PATO:0000921) of a bulb (PO:0025356).
synonym: Bulb horizontal diameter, exact
- bulb color TO:0001130:  A bulb morphology trait (TO:0001126) which is the color (PATO:0000014) of a bulb (PO:0025356).

**Comment by austinmeier** [comment]
Thanks Lol!
