### ISSUE TITLE
[BUG] TO purls are broken

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [Planteome/plant-trait-ontology#506]
When I checked out your purls today, I noticed that the don't seem to resolve correctly. I always end up at Ontobee's "Term Not Found" page. An example link is this: http://purl.obolibrary.org/obo/TO_0000283
I'm not sure if this is an Ontobee issue or an issue with the yml configuration of TO at OBO Foundry though.

**Comment by cooperl09** [comment]
It looks like there are some issues at the OntoBee end. I saw you opened an issues there. https://github.com/OntoZoo/ontobee/issues/204
If you want to browse the latest versions of our ontologies, you can do so at https://dev.planteome.org/amigo
Downloads are available in GitHub or at OboFoundry
Thanks!

**Comment by cooperl09** [comment]
Closing as this has been resolved
