### ISSUE TITLE
Tuber trait terms

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#56]
These terms have been added by the request of previous tracker item:https://sourceforge.net/tracker/?func=detail&aid=3487511&group\_id=76834&atid=835557.  These will  all be children of the new term: subterranean tuber anatomy and morphology trait [(TO:0000742](http://purl.obolibrary.org/obo/%28TO_0000742))

===requested terms and suggested def'ns:===
tuber shape- The shape of the tuber
tuber size- The physical size of the tuber
tuber appearance- The overall appearance of the tuber. A 1-9 scale is used, with 1 the lowest score (very poor) and 9 the highest (excellent)
tuber mass- The mass of the tuber

\* Proposed new term and def'n: subterranean tuber shape [(TO:0000743](http://purl.obolibrary.org/obo/%28TO_0000743)): A subterranean tuber anatomy and morphology trait [(TO:0000742](http://purl.obolibrary.org/obo/%28TO_0000742)) which is associated with the shape of a subterranean tuber [(PO:0004547](http://purl.obolibrary.org/obo/%28PO_0004547)).
broad synonym: tuber shape
refer to PATO shape: [PATO:0000052](http://purl.obolibrary.org/obo/PATO_0000052)

\* Proposed new term and def'n: subterranean tuber size [(TO:0000744](http://purl.obolibrary.org/obo/%28TO_0000744)): A subterranean tuber anatomy and morphology trait [(TO:0000742](http://purl.obolibrary.org/obo/%28TO_0000742)) which is associated with the size of a subterranean tuber [(PO:0004547](http://purl.obolibrary.org/obo/%28PO_0004547)).
refer to PATO size: [PATO:0000117](http://purl.obolibrary.org/obo/PATO_0000117)
broad synonym: tuber size

\* Proposed new term and def'n: subterranean tuber appearance [(TO:0000745](http://purl.obolibrary.org/obo/%28TO_0000745)): A subterranean tuber anatomy and morphology trait [(TO:0000742](http://purl.obolibrary.org/obo/%28TO_0000742)) which is associated with the appearance of a subterranean tuber [(PO:0004547](http://purl.obolibrary.org/obo/%28PO_0004547)).
comment: A 1-9 scale is used to score the overall appearance of the tuber, with 1 the lowest score (very poor) and 9 the highest (excellent)
broad synonym: tuber appearance
No PATO reference for refer to appearance

*Proposed new term and def'n: subterranean tuber mass [(TO:0000746](http://purl.obolibrary.org/obo/%28TO_0000746)): A subterranean tuber anatomy and morphology trait [(TO:0000742](http://purl.obolibrary.org/obo/%28TO_0000742)) which is associated with the mass of a subterranean tuber [(PO:0004547](http://purl.obolibrary.org/obo/%28PO_0004547)).
broad synonym: tuber mass
refers to PATO mass: [PATO:0000125](http://purl.obolibrary.org/obo/PATO_0000125) 

Reported by: cooperl09

Original Ticket: [obo/plant-trait-ontology-to-requests/55](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/55)

**Comment by cooperl09** [comment]
Moved tuber morphology trait (TO:0000741) to be a child of plant axis morphology trait (TO:0000738). 
Revised def'n: 
was: A branch morphology trait (TO:0000739) which is quality of a tuber (PO:0004543).
Revised: A plant axis morphology trait (TO:0000738) which is quality of a tuber (PO:0004543).

subterranean tuber morphology trait (TO:0000742) and child terms renamed: 
- subterranean tuber morphology trait (TO:0000742) --> subterranean shoot axis tuber morphology trait (TO:0000742).
Child terms:
-  subterranean tuber appearance (TO:0000745) -->  subterranean shoot axis tuber appearance 
-  subterranean tuber shape ( TO:0000743) --> subterranean shoot axis tuber shape
-  subterranean tuber size  TO:0000744) -->  subterranean shoot axis tuber size
-  subterranean tuber mass (TO:0000746) -->  subterranean shoot axis tuber mass
* changed synonyms from RELATED to BROAD, as they could apply to other kids of tubers
