### ISSUE TITLE
shoot system morphology trait (TO:0000077) and sub-classes

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#57]
I propose the following:  we need to rename and redefine this class to align it with the PO hierarchy of shoot system and make it consistent.  Plus, as it stands right now it contains a hodgepodge of child terms, some of which will need to be rearranged.

current name and def'n: shoot anatomy and morphology trait [(TO:0000077](http://purl.obolibrary.org/obo/%28TO_0000077)): Traits associated with changes in the anatomy or structure of the shoot and its parts.

Propose revised name and def'n: shoot system anatomy and morphology trait [(TO:0000077](http://purl.obolibrary.org/obo/%28TO_0000077)): An anatomy and morphology trait [(TO:0000017](http://purl.obolibrary.org/obo/%28TO_0000017)) which is associated with a shoot system [(PO:0009006](http://purl.obolibrary.org/obo/%28PO_0009006)).

The PO class shoot system [(PO:0009006](http://purl.obolibrary.org/obo/%28PO_0009006)) includes several important  sub-classes such as: bud, primary shoot, reproductive shoot system (inflorescence, flower, spikelet, infructescence, reproductive bud, etc) and others.

Reported by: cooperl09

Original Ticket: [obo/plant-trait-ontology-to-requests/56](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/56)

**Comment by cooperl09** [comment]
Moved from Issue #157 

stem number (TO:0000953): Revised parent and def'n
Was: stem number (TO:0000953): A stem anatomy and morphology trait (TO:0000361) which is associated with the number of stems (PO:0009047).
Xrefs to: number (PATO:0001555); TO_GIT:157
narrow synonym: stalk weight

Revised:
stem number (TO:0000953): A shoot system anatomy and morphology trait (TO:0000077) which is associated with the number of stems (PO:0009047).

    removed narrow synonym: stalk weight

**Comment by cooperl09** [comment]
Comment from Issue #80:
Re: 
once 'stem number' trait will be created. Please create a relationship with 'shoot development trait' (TO:0000654)

Original comment by: alexandraviel

**Comment by ejohnson1** [comment]
shoot system anatomy and morphology trait (TO:0000077): Revised name and def'n
Was: A collective plant organ structure anatomy and morphology trait (TO:0000842) which is associated with a shoot system (PO:0009006).
New: A collective plant organ structure morphology trait (TO:0000842) which is a quality of a shoot system (PO:0009006).

**Comment by ejohnson1** [comment]
reproductive shoot system anatomy and morphology trait (TO:0000786): Revised name and def'n
Was: reproductive shoot system anatomy and morphology trait (TO:0000786), A shoot system anatomy and morphology trait (TO:0000077) that is associated with a reproductive shoot system (PO:0025082).
New: reproductive shoot system morphology trait (TO:0000786), A shoot system morphology trait (TO:0000077) that is a quality of a reproductive shoot system (PO:0025082).
