### ISSUE TITLE
cardinal organ part

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#63]
Proposed new term: cardinal organ part anatomy and morphology trait [(TO:0000754](http://purl.obolibrary.org/obo/%28TO_0000754))

Proposed definition:An anatomy and morphology trait [(TO:0000017](http://purl.obolibrary.org/obo/%28TO_0000017)) which is associated with a cardinal organ part [(PO:0025001](http://purl.obolibrary.org/obo/%28PO_0025001)).

Reported by: lauramooray

Original Ticket: [obo/plant-trait-ontology-to-requests/62](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/62)

**Comment by ejohnson1** [comment]
Revised name and def'n: cardinal organ part anatomy and morphology trait (TO:0000754)
Was: cardinal organ part anatomy and morphology trait (TO:0000754), A cardinal organ part of a multi-tissue plant structure anatomy and morphology trait (TO:0000754) which is associated with a cardinal organ part (TO:0000754).
New: cardinal organ part morphology trait (TO:0000754), A cardinal organ part of a multi-tissue plant structure morphology trait (TO:0000837) which is a quality of a cardinal organ part (PO:0025001).

**Comment by phismith** [comment]
Something is going wrong here

New: cardinal organ part morphology trait (TO:0000754) =def. A cardinal
organ part of a multi-tissue plant structure morphology trait (TO:0000837)
which is a quality of a cardinal organ part (PO:0025001)

A cardinal organ cannot be a part of a trait

I would prefer something like:


=def. A morphology trait that is a quality of a cardinal organ part

BS
