### ISSUE TITLE
shoot axis internode morphology traits (TO:0000755)- hypocotyl and mesocotyl morphology traits

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#64]
Hypocotyl terms requested from #50 

Proposed new child of cardinal organ part anatomy and morphology trait (TO:0000754):
- shoot internode anatomy and morphology trait (TO:0000755): proposed definition: A cardinal organ part anatomy and morphology trait (TO:0000754) which is associated with a shoot internode (PO_0005005). 

Proposed new child of shoot internode anatomy and morphology trait (TO:0000755):
- stem internode anatomy and morphology trait (TO:0000756): A shoot internode anatomy and morphology trait (TO:0000755) which is associated with a stem internode (PO:0020142). 

Proposed new children of stem internode anatomy and morphology trait (TO:0000756):
- hypocotyl anatomy and morphology trait (TO_0000757): A stem internode anatomy and morphology trait(TO:0000756) which is associated with a hypocotyl (PO_0020100).
- mesocotyl anatomy and morphology trait (TO_0000758): A stem internode anatomy and morphology trait (TO:0000756) which is associated with a mesocotyl (PO:0020037).

Proposed new children of hypocotyl anatomy and morphology trait (TO:0000757):
- hypocotyl length (TO:0006065): A hypocotyl anatomy and morphology trait (TO:0000757) which is associated with the length of a hypocotyl (PO:0020100). 
  Refer to length [PATO:0000122](http://purl.obolibrary.org/obo/PATO_0000122) 
- hypocotyl color [TO:0000759](http://purl.obolibrary.org/obo/TO_0000759): A hypocotyl anatomy and morphology trait [TO:0000757](http://purl.obolibrary.org/obo/TO_0000757) which is associated with the color of a hypocotyl [PO:0020100](http://purl.obolibrary.org/obo/PO_0020100). 
  Refer to color [PATO:0000014](http://purl.obolibrary.org/obo/PATO_0000014) 

Proposed new child of mesocotyl anatomy and morphology trait [TO:0000758](http://purl.obolibrary.org/obo/TO_0000758):
- mesocotyl length [TO:0000544](http://purl.obolibrary.org/obo/TO_0000544): A mesocotyl anatomy and morphology trait [TO:0000758](http://purl.obolibrary.org/obo/%28TO_0000758) which is associated with the length of a mesocotyl [PO:0020037](http://purl.obolibrary.org/obo/PO_0020037). 
  Refer to length [PATO:0000122](http://purl.obolibrary.org/obo/PATO_0000122) 

Reported by: lauramooray

Original Ticket: [obo/plant-trait-ontology-to-requests/63](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/63); [obo/plant-trait-ontology-to-requests/63](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/50)

**Comment by ejohnson1** [comment]
Revised name and def'n: cardinal organ part anatomy and morphology trait (TO:0000754)
Was: cardinal organ part anatomy and morphology trait (TO:0000754), A cardinal organ part of a multi-tissue plant structure anatomy and morphology trait (TO:0000754) which is associated with a cardinal organ part (TO:0000754).
New: cardinal organ part morphology trait (TO:0000754), A cardinal organ part of a multi-tissue plant structure morphology trait (TO:0000837) which is a quality of a cardinal organ part (PO:0025001).

**Comment by maxglycine** [comment]
Need to define what "size" means in "seedling hypocotyl size" in "TO:0000781"

**Comment by cooperl09** [comment]
Revisions to the shoot axis internode morphology trait (TO:0000755)
Was:
* shoot internode morphology trait (TO:0000755): A cardinal organ part anatomy and morphology trait (TO:0000754) which is associated with a shoot internode (PO_0005005).

* Revised: shoot axis internode morphology trait (TO:0000755):
A cardinal organ part morphology trait (TO:0000754) which is a quality of a shoot axis internode (PO:0005005).
_____________________________________________

* stem internode morphology trait (TO:0000756): A shoot internode morphology trait (TO:0000755) which is associated with a stem internode (PO:0020142).

Revised:  A shoot axis internode morphology trait (TO:0000755) which is quality of a stem internode (PO:0020142).

**Comment by cooperl09** [comment]
stem internode color (TO:0000426)- revised name and definition- had no is_a parent

Was: internode color (TO:0000426): def: "Color of the stem internode."
Revised: stem internode color (TO:0000426)- def: "A stem internode morphology trait (TO:0000756) which is the color of the stem internode (PO:0020142)."
