### ISSUE TITLE
bacterial blight disease resistance

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#66]
Suggested term:

\[Term\]
id: TO:xxxxxxx
name: bacterial blight disease resistance
is\_a: [TO:0000315](http://purl.obolibrary.org/obo/TO_0000315) \! bacterial disease resistance

after adding such term, the term 'rice bacterial blight disease resistance' [\(TO:0000175](http://purl.obolibrary.org/obo/\(TO_0000175)\) should be moved so that it becomes a child of 'bacterial blight disease resistance'  \(following the same logic as in the fungal case: [TO:0000664](http://purl.obolibrary.org/obo/TO_0000664)\)

Reported by: easr

Original Ticket: [obo/plant-trait-ontology-to-requests/65](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/65)

**Comment by austinmeier** [comment]
Note: bacterial blight disease resistance is (TO:0000770)
