### ISSUE TITLE
Seed Coat anatomical part request

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#76]
Seed anatomy and morphology trait.  Title: "Seed coat" Def:"The outer cellular layer\(s\) of a seed that enclose the embryo." Comment="The number of cellular layers vary among taxa."  Synonym="testa" 

Note: you have Seed coat color and Seed coat color:Seed coat spots but no parent term of Seed coat.

Reported by: maxglycine

Original Ticket: [obo/plant-trait-ontology-to-requests/75](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/75)

**Comment by austinmeier** [comment]
There is an existing term in the PO for seed coat (PO:0009088): A portion of plant tissue that is the covering of a seed derived from ovular - mainly integumentary - tissue.

seed coat length (TO:0000880), seed coat hardness (TO:0000889), and seed coat luster (TO:0000888) all exist under the parent- seed coat anatomy and morphology trait (TO:0000838).
