### ISSUE TITLE
Stem shape

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#80]
Def="The shape of a stem"  Comment="Values are usually terms given to specific shapes ie "faciated stem" to describe a stem that is flat in shape instead of round"

Reported by: maxglycine

Original Ticket: [obo/plant-trait-ontology-to-requests/79](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/79)

**Comment by austinmeier** [comment]
stem number (TO:0000953): A shoot system anatomy and morphology trait (TO:0000077) which is associated with the number of stems (PO:0009047).
child_of shoot system anatomy and morphology trait (TO:0000077)

Please open a new tracker to continue discussion on potential "stem termination" term.
