### ISSUE TITLE
hilum color trait term request

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#81]
Seed anatomy and morphology trait
Hilum color  Def:"The color of the hilum of a seed"

Reported by: maxglycine

Original Ticket: [obo/plant-trait-ontology-to-requests/80](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/80)

**Comment by austinmeier** [comment]
created terms:  hilum anatomy and morphology trait (TO:0000967): A seed anatomy and morphology trait (TO:0000184) which is associated with a hilum (PO:0020063) 
and hilum color (TO:0000968):A hilum anatomy and morphology trait (TO:0000967) which is associated with the color of a hilum (PO:0020063).

**Comment by cooperl09** [comment]
hilum color- was added as a child of hilum morphology (TO:0000967):
hilum color (TO:0000968): A hilum morphology trait (TO:0000967) which is the color of a hilum (PO:0020063).
