### ISSUE TITLE
plant height  (TO:0000207)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#84]
plant height [(TO:0000207](http://purl.obolibrary.org/obo/%28TO_0000207))  currently has two is_a parents: 'shoot system anatomy and morphology trait' ; 'stature and vigor trait'

plant height :  Actual measurement of plant height from soil surface to the highest point in plant as identified in the study.

I propose this should just be a "stature and vigor trait, rather than keeping it in the Anatomy and Morphology hierarchy as well..  

Reported by: cooperl09

Original Ticket: [obo/plant-trait-ontology-to-requests/83](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/83)

**Comment by cooperl09** [comment]
Revised definition:
Was: 
plant height (TO:0000207): A height related trait (TO:0000171) which is the height of a whole plant (PO:0000003). 
Revised: 
A height trait (TO:0000171) which is the height of a whole plant (PO:0000003). 
Comment: Refers to: height (PATO_0000119): A 1-D extent quality inhering in a bearer by virtue of the bearer's vertical dimension of extension.

**Comment by cooperl09** [comment]
Moved plant height (TO:0000207) to be a child of whole plant morphology trait (TO:0000398).

Was: 
plant height (TO:0000207): A height trait (TO:0000171) which is the height of a whole plant (PO:0000003). 
Comment: Refers to: height (PATO_0000119): A 1-D extent quality inhering in a bearer by virtue of the bearer's vertical dimension of extension.

Revised: 
plant height (TO:0000207): A whole plant morphology trait (TO:0000398) which is the height of a whole plant (PO:0000003). 
Comment: Refers to: height (PATO_0000119): A 1-D extent quality inhering in a bearer by virtue of the bearer's vertical dimension of extension.

See also# 367
