### ISSUE TITLE
plant color (TO:0000708)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#85]
plant color  [(TO:0000708](http://purl.obolibrary.org/obo/%28TO_0000708)): currently is a shoot system anatomy and morphology trait , I propse it should be is a  'stature and vigor trait'

Current def'n: The color of the plant. 

Reported by: cooperl09

Original Ticket: [obo/plant-trait-ontology-to-requests/84](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/84)

**Comment by cooperl09** [comment]
Moved plant color (TO:0000708) to be a child of whole plant morphology trait (TO:0000398).

Was: plant color (TO:0000708):  A stature and vigor trait (TO:0000133) which is the color of a whole plant (PO:0000003). 

Revised: A whole plant morphology trait (TO:0000398) which is the color of a whole plant (PO:0000003). 
Added comment: Refer to color (PATO:0000014): A composite chromatic quality composed of hue, saturation and intensity parts.

see also #367
