### ISSUE TITLE
Head anatomy and morphology traits

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#92]
anatomy and morphology trait - [TO:0000017](http://purl.obolibrary.org/obo/TO_0000017)
Proposed new children of this term + definitions: Head anatomy and morphology trait :
-&gt; head shape- shape of the head, measured in
-&gt; head density - density of the head, measured in
-&gt; head depth -  depth of the head, measured in 
-&gt; head diameter - diameter of the head, measured in
-&gt; head weight - weight of the head, measured in
-&gt; head width - width of the head, measured in 
-&gt; head texture - texture of the head
-&gt; head color - color of the head
-&gt; hair presence - presence of hairs on the head

Reported by: alexandraviel

Original Ticket: [obo/plant-trait-ontology-to-requests/91](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/91)

**Comment by cooperl09** [comment]
All these terms were added as synonyms to the respective trait terms:
- inflorescence color (TO:0000581), added narrow synonym- head color
- inflorescence density (TO:0000800), added narrow synonym- head density
- inflorescence depth (TO:0000801), added narrow synonym- head depth
- inflorescence diameter (TO:0000802), added narrow synonym- head diameter

- inflorescence shape (TO:0000268), added narrow synonym- head shape
- inflorescence texture (TO:0000805), added head texture as a narrow synonym
- inflorescence weight (TO:0000803), added head weight as a narrow synonym
- inflorescence width (TO:0000804), added head width as a narrow synonym
- inflorescence hairiness (TO:0000971), added narrow synonym- head hairiness
