### ISSUE TITLE
Pseudostem anatomy and morphology traits

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#94]
Stem anatomy and morphology trait:
Proposed new children of this term + definitions: Pseudostem anatomy and morphology trait
-&gt; pseudostem length- length of the pseudostem, measured in 
-&gt; pseudostem shape - shape of the pseudostem, measured in 
-&gt; pseudostem color - Color of the external sheaths of the pseudostem
-&gt; pseudostem diameter - diameter of the pseudostem, measured in 
[\(PO:0025248](http://purl.obolibrary.org/obo/\(PO_0025248) : pseudostem\)

Reported by: alexandraviel

Original Ticket: [obo/plant-trait-ontology-to-requests/93](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/93)

**Comment by cooperl09** [comment]
Moved pseudostem anatomy and morphology trait  and child terms to the correct parent- is_a collective organ part structure anatomy and morphology trait (TO:0000841).

pseudostem anatomy and morphology trait (TO:0000807):
-  was: A stem anatomy and morphology trait (TO:0000361) which is associated with a pseudostem (PO:0025248). 
Revised:  A collective organ part structure anatomy and morphology trait (TO:0000841) which is associated with the qualities of a pseudostem (PO:0025248).

Fixed xrefs to GitHub tracker on all five child terms : should be TO_GIT: 94, not 95,

**Comment by ejohnson1** [comment]
Revised name and def'n of: pseudostem anatomy morphology trait (TO:0000807)
Was: pseudostem anatomy morphology trait (TO:0000807), A collective organ part structure anatomy and morphology trait (TO:0000841) which is associated with the qualities of a pseudostem (PO:0025248).
New: pseudostem morphology trait (TO:0000807), A collective organ part structure morphology trait (TO:0000841) which is a quality of a pseudostem (PO:0025248).

Revised def'n of: psuedostem color (TO:0000810)
Was: A pseudostem anatomy and morphology trait (TO:0000807) which is associated with the color of a pseudostem (PO:0025248). 
New: A pseudostem morphology trait (TO:0000807) that is the color of a pseudostem (PO:0025248).

Revised def'n of: pseudostem diameter (TO:0000811)
Was: A pseudostem anatomy and morphology trait (TO:0000807) which is associated with the diameter of a pseudostem (PO:0025248).
New: A pseudostem morphology trait (TO:0000807) that is the diameter of a pseudostem (PO:0025248).

Revised def'n of: pseudostem length (TO:0000808)
Was: A pseudostem anatomy and morphology trait (TO:0000807) which is associated with the length of a pseudostem (PO:0025248).
New: A pseudostem morphology trait (TO:0000807) that is the length of a pseudostem (PO:0025248).

Revised def'n of: pseudostem shape (TO:0000809)
Was: A pseudostem anatomy and morphology trait (TO:0000807) which is associated with the shape of a pseudostem (PO:0025248).
New: A pseudostem morphology trait (TO:0000807) that is the shape of a pseudostem (PO:0025248).
