### ISSUE TITLE
pseudostem traits

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#96]
Proposed new parent term and definition:
- pseudostem anatomy and morphology trait: A stem anatomy and morphology trait [(TO:0000361](http://purl.obolibrary.org/obo/%28TO_0000361)) wich is associated with a pseudostem [(PO:0025248](http://purl.obolibrary.org/obo/%28PO_0025248)).

Proposed new children of term + definitions:
- pseudostem length: A pseudostem anatomy and morphology trait (TO:id) which is associated with the length of a pseudostem [(PO:0025248](http://purl.obolibrary.org/obo/%28PO_0025248)). Refer to length [PATO:0000122](http://purl.obolibrary.org/obo/PATO_0000122)
- pseudostem shape: A pseudostem anatomy and morphology trait (TO:id) which is associated with the shape of a pseudostem [(PO:0025248](http://purl.obolibrary.org/obo/%28PO_0025248)). Refer to shape [PATO:0000052](http://purl.obolibrary.org/obo/PATO_0000052)
- pseudostem color: A pseudostem anatomy and morphology trait (TO:id) which is associated with the color of a pseudostem [(PO:0025248](http://purl.obolibrary.org/obo/%28PO_0025248)). Refer to color [PATO:0000014](http://purl.obolibrary.org/obo/PATO_0000014)
- pseudostem diameter: A pseudostem anatomy and morphology trait (TO:id) which is associated with the diameter of a pseudostem [(PO:0025248](http://purl.obolibrary.org/obo/%28PO_0025248)). Refer to diameter [PATO:0001334](http://purl.obolibrary.org/obo/PATO_0001334)

Reported by: lauramooray

Original Ticket: [obo/plant-trait-ontology-to-requests/95](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/95)

**Comment by cooperl09** [comment]
See comments and revisions on #94.
