### ISSUE TITLE
inflorescence morphology traits and child terms

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-trait-ontology#97]
Proposed new child of inflorescence anatomy and morphology + definition:
- head anatomy and morphology trait: An inflorescence anatomy and morphology trait [(TO:0000373](http://purl.obolibrary.org/obo/%28TO_0000373)) which is associated with the head of a plant.

Proposed new children of this term + definitions:
- head shape: A head anatomy and morphology trait (TO:id) which is associated with the shape of a head. Refer to shape [PATO:0000052](http://purl.obolibrary.org/obo/PATO_0000052)
- head density: A head anatomy and morphology trait (TO:id) which is associated with the density of a head. Refer to absolute density [PATO:0001070](http://purl.obolibrary.org/obo/PATO_0001070)
- head depth: A head anatomy and morphology trait (TO:id) which is associated with the depth of a head. Refer to depth [PATO:0001595](http://purl.obolibrary.org/obo/PATO_0001595)
- head diameter: A head anatomy and morphology trait (TO:id) which is associated with the diameter of a head. Refer to diameter [PATO:0001334](http://purl.obolibrary.org/obo/PATO_0001334)
- head weight : A head anatomy and morphology trait (TO:id) which is associated with the weight of a head. Refer to weight [PATO:0000128](http://purl.obolibrary.org/obo/PATO_0000128)
- head width: A head anatomy and morphology trait (TO:id) which is associated with the width of a head. Refer to width [PATO:0000921](http://purl.obolibrary.org/obo/PATO_0000921)
- head texture: A head anatomy and morphology trait (TO:id) which is associated with the texture of a head. Refer to texture [PATO:0000150](http://purl.obolibrary.org/obo/PATO_0000150)
- head color: A head anatomy and morphology trait (TO:id) which is associated with the color of a head. Refer to color [PATO:0000014](http://purl.obolibrary.org/obo/PATO_0000014)
- head presence: A head anatomy and morphology trait (TO:id) which is associated with the presence of a head. Refer to presence value [PATO:0000458](http://purl.obolibrary.org/obo/PATO_0000458)

Reported by: lauramooray

Original Ticket: [obo/plant-trait-ontology-to-requests/96](https://sourceforge.net/p/obo/plant-trait-ontology-to-requests/96)

**Comment by cooperl09** [comment]
panicle density (TO:0000970): An inflorescence density (TO:0000800) trait associated with a panicle (PO:0009049).
is_a  panicle anatomy and morphology trait (TO:0000847) 

inflorescence height (TO:0000682):- moved to be an inflorescence anatomy and morphology trait (TO:0000373), was a height related trait (TO:0000171) .
Revised def'n: An inflorescence anatomy and morphology trait (TO:0000373)
 which is associated with the height of an inflorescence (PO:0009049) measured from ground to the attachment point.
 Added: head height (narrow); Added Xref  to TO_GIT:97  

New term: inflorescence hairiness (TO:0000971): An inflorescence anatomy and morphology trait (TO:0000373) which is associated with the presence or absence of hairs on an inflorescence (PO:0009049).

**Comment by ejohnson1** [comment]
inflorescence anatomy and morphology trait (TO:0000373):Revised name and def'n 
Was: inflorescence anatomy and morphology trait (TO:0000373), A reproductive shoot system anatomy and morphology trait (TO:0000786) that is associated with the qualities of an inflorescence (PO:0009049).
New: inflorescence morphology trait (TO:0000373), A reproductive shoot system morphology trait (TO:0000786) that is a quality of an inflorescence (PO:0009049).

**Comment by cooperl09** [comment]
Revised name and definiton:
inflorescence height (TO:0000682): A height related trait (TO:0000171) which is associated with the height of an inflorescence (PO:0009049) measured from ground to the attachment point.
(TO_GIT: 366)

Revised name and definition:
inflorescence position (TO:0000682): An inflorescence morphology trait (TO:0000373) which is the position of an inflorescence (PO:0009049) on a plant.  

Comment: Refers to: position (PATO_0000140): A spatial quality inhering in a bearer by virtue of the bearer's spatial location relative to other objects in the vicinity. Usually measured from the ground.  This is often  measured from the ground to the point where the inflorescence is attached.
modified equivalence axiom:  position and (inheres_in some inflorescence)
